import { describe, test, expect } from 'bun:test'
import { join } from 'path'

const TEST_DIR = join(import.meta.dir, '__test_domains')
const EXTRACT_SCRIPT = join(import.meta.dir, 'extract-types.ts')

/**
 * Run the extraction script in a test directory
 */
async function runExtraction(testDir: string): Promise<{ stdout: string; stderr: string; exitCode: number }> {
  const proc = Bun.spawn(['bun', 'run', EXTRACT_SCRIPT], {
    cwd: testDir,
    env: { ...Bun.env, DOMAINS_DIR: testDir },
    stdout: 'pipe',
    stderr: 'pipe',
  })

  const [stdout, stderr] = await Promise.all([
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
  ])

  const exitCode = await proc.exited

  return { stdout, stderr, exitCode }
}

/**
 * Create a test environment with domain markdown files
 */
async function setupTestEnv(files: Record<string, string>): Promise<string> {
  const testDir = `${TEST_DIR}_${Date.now()}`
  const scriptsDir = join(testDir, 'scripts')

  // Create directories using mkdir command
  const mkdirProc = Bun.spawn(['mkdir', '-p', scriptsDir], {
    stdout: 'pipe',
    stderr: 'pipe',
  })
  await mkdirProc.exited

  // Copy extraction script to test directory
  const scriptContent = await Bun.file(EXTRACT_SCRIPT).text()
  await Bun.write(join(testDir, 'scripts', 'extract-types.ts'), scriptContent)

  // Write test markdown files
  for (const [filename, content] of Object.entries(files)) {
    await Bun.write(join(testDir, filename), content)
  }

  return testDir
}

/**
 * Clean up test environment
 */
async function cleanupTestEnv(testDir: string) {
  const proc = Bun.spawn(['rm', '-rf', testDir], {
    stdout: 'pipe',
    stderr: 'pipe',
  })
  await proc.exited
}

describe('extract-types script', () => {
  test('basic extraction: single type in one file', async () => {
    const testDir = await setupTestEnv({
      'test.md': `# Test Domain

\`\`\`typescript
export type TestType = {
  id: string
  name: string
}
\`\`\`
`,
    })

    const result = await runExtraction(testDir)
    expect(result.exitCode).toBe(0)

    const output = await Bun.file(join(testDir, 'types', 'test.ts')).text()
    expect(output).toContain('export type TestType')
    expect(output).toContain('id: string')
    expect(output).toContain('name: string')
    expect(output).toContain('DO NOT EDIT THIS FILE DIRECTLY')
    expect(output).toContain('domains/test.md')

    await cleanupTestEnv(testDir)
  })

  test('multiple code blocks: combines into single namespace', async () => {
    const testDir = await setupTestEnv({
      'domain.md': `# Domain

First type:
\`\`\`typescript
export type TypeA = { a: string }
\`\`\`

Second type:
\`\`\`typescript
export type TypeB = { b: number }
\`\`\`
`,
    })

    const result = await runExtraction(testDir)
    expect(result.exitCode).toBe(0)

    const output = await Bun.file(join(testDir, 'types', 'domain.ts')).text()
    expect(output).toContain('export type TypeA')
    expect(output).toContain('export type TypeB')

    await cleanupTestEnv(testDir)
  })

  test('file generation: multiple domains create separate files', async () => {
    const testDir = await setupTestEnv({
      'auth.md': `\`\`\`typescript
export type User = { id: string }
\`\`\``,
      'books.md': `\`\`\`typescript
export type Book = { title: string }
\`\`\``,
    })

    const result = await runExtraction(testDir)
    expect(result.exitCode).toBe(0)

    const authOutput = await Bun.file(join(testDir, 'types', 'auth.ts')).text()
    expect(authOutput).toContain('export type User')

    const booksOutput = await Bun.file(join(testDir, 'types', 'books.ts')).text()
    expect(booksOutput).toContain('export type Book')

    await cleanupTestEnv(testDir)
  })

  test('export preservation: maintains all export types', async () => {
    const testDir = await setupTestEnv({
      'exports.md': `\`\`\`typescript
export type TypeA = string
export interface InterfaceB { x: number }
export enum EnumC { A, B, C }
export class ErrorD extends Error {}
export function guardE(x: unknown): x is TypeA { return typeof x === 'string' }
\`\`\``,
    })

    const result = await runExtraction(testDir)
    expect(result.exitCode).toBe(0)

    const output = await Bun.file(join(testDir, 'types', 'exports.ts')).text()
    expect(output).toContain('export type TypeA')
    expect(output).toContain('export interface InterfaceB')
    expect(output).toContain('export enum EnumC')
    expect(output).toContain('export class ErrorD')
    expect(output).toContain('export function guardE')

    await cleanupTestEnv(testDir)
  })

  test('idempotency: running twice produces identical output', async () => {
    const testDir = await setupTestEnv({
      'test.md': `\`\`\`typescript
export type Test = { value: number }
\`\`\``,
    })

    const result1 = await runExtraction(testDir)
    expect(result1.exitCode).toBe(0)
    const output1 = await Bun.file(join(testDir, 'types', 'test.ts')).text()

    const result2 = await runExtraction(testDir)
    expect(result2.exitCode).toBe(0)
    const output2 = await Bun.file(join(testDir, 'types', 'test.ts')).text()

    expect(output1).toBe(output2)

    await cleanupTestEnv(testDir)
  })

  test('edge case: file with no code blocks', async () => {
    const testDir = await setupTestEnv({
      'empty.md': `# Empty Domain

This has no TypeScript code blocks.
`,
      'valid.md': `\`\`\`typescript
export type Valid = { ok: true }
\`\`\``,
    })

    const result = await runExtraction(testDir)
    expect(result.exitCode).toBe(0) // Should still succeed

    // empty.ts should not exist
    const emptyExists = await Bun.file(join(testDir, 'types', 'empty.ts')).exists()
    expect(emptyExists).toBe(false)

    // valid.ts should exist
    const validOutput = await Bun.file(join(testDir, 'types', 'valid.ts')).text()
    expect(validOutput).toContain('export type Valid')

    await cleanupTestEnv(testDir)
  })

  test('edge case: README.md is excluded', async () => {
    const testDir = await setupTestEnv({
      'README.md': `\`\`\`typescript
export type ShouldNotAppear = { bad: true }
\`\`\``,
      'domain.md': `\`\`\`typescript
export type ShouldAppear = { good: true }
\`\`\``,
    })

    const result = await runExtraction(testDir)
    expect(result.exitCode).toBe(0)

    // README.ts should not exist
    const readmeExists = await Bun.file(join(testDir, 'types', 'README.ts')).exists()
    expect(readmeExists).toBe(false)

    // domain.ts should exist and contain the right type
    const domainOutput = await Bun.file(join(testDir, 'types', 'domain.ts')).text()
    expect(domainOutput).toContain('ShouldAppear')
    expect(domainOutput).not.toContain('ShouldNotAppear')

    await cleanupTestEnv(testDir)
  })

  test('caching: second run uses cache for unchanged files', async () => {
    const testDir = await setupTestEnv({
      'test.md': `\`\`\`typescript
export type Test = { cached: true }
\`\`\``,
    })

    // First run
    const result1 = await runExtraction(testDir)
    expect(result1.exitCode).toBe(0)
    expect(result1.stdout).toContain('extracting types')

    // Second run (should use cache)
    const result2 = await runExtraction(testDir)
    expect(result2.exitCode).toBe(0)
    expect(result2.stdout).toContain('using cached extraction')

    await cleanupTestEnv(testDir)
  })

  test('caching: detects file changes and re-extracts', async () => {
    const testDir = await setupTestEnv({
      'test.md': `\`\`\`typescript
export type Test = { version: 1 }
\`\`\``,
    })

    // First run
    const result1 = await runExtraction(testDir)
    expect(result1.exitCode).toBe(0)

    // Modify file
    await Bun.write(
      join(testDir, 'test.md'),
      `\`\`\`typescript
export type Test = { version: 2 }
\`\`\``
    )

    // Second run (should re-extract)
    const result2 = await runExtraction(testDir)
    expect(result2.exitCode).toBe(0)
    expect(result2.stdout).toContain('extracting types')

    const output = await Bun.file(join(testDir, 'types', 'test.ts')).text()
    expect(output).toContain('version: 2')

    await cleanupTestEnv(testDir)
  })

  test('error handling: exits with error code when no .md files found', async () => {
    const testDir = `${TEST_DIR}_${Date.now()}`
    const scriptsDir = join(testDir, 'scripts')

    // Create directories using mkdir command
    const mkdirProc = Bun.spawn(['mkdir', '-p', scriptsDir], {
      stdout: 'pipe',
      stderr: 'pipe',
    })
    await mkdirProc.exited

    const scriptContent = await Bun.file(EXTRACT_SCRIPT).text()
    await Bun.write(join(testDir, 'scripts', 'extract-types.ts'), scriptContent)

    const result = await runExtraction(testDir)
    expect(result.exitCode).toBe(0) // Script exits cleanly when no files found

    await cleanupTestEnv(testDir)
  })

  test('filtering: only exports are included, example code excluded', async () => {
    const testDir = await setupTestEnv({
      'domain.md': `# Domain

Type definitions:
\`\`\`typescript
export type User = {
  id: string
  name: string
}

export interface Session {
  userId: string
  token: string
}
\`\`\`

Usage example:
\`\`\`typescript
import { User } from './domain'

// Example usage - should NOT be included
const user: User = {
  id: '123',
  name: 'Alice',
}

console.log(user.name)
\`\`\`
`,
    })

    const result = await runExtraction(testDir)
    expect(result.exitCode).toBe(0)

    const output = await Bun.file(join(testDir, 'types', 'domain.ts')).text()

    // Should include exports
    expect(output).toContain('export type User')
    expect(output).toContain('export interface Session')

    // Should NOT include example code
    expect(output).not.toContain('import { User }')
    expect(output).not.toContain('const user: User')
    expect(output).not.toContain('console.log')

    await cleanupTestEnv(testDir)
  })

  test('filtering: multi-line exports are preserved completely', async () => {
    const testDir = await setupTestEnv({
      'types.md': `# Types

Definition:
\`\`\`typescript
export interface ComplexType {
  nested: {
    deeply: {
      values: string[]
    }
  }
  method(): void
}
\`\`\`

Usage example:
\`\`\`typescript
const example = { nested: { deeply: { values: [] } } }
\`\`\``,
    })

    const result = await runExtraction(testDir)
    expect(result.exitCode).toBe(0)

    const output = await Bun.file(join(testDir, 'types', 'types.ts')).text()

    // Should include entire multi-line export
    expect(output).toContain('export interface ComplexType')
    expect(output).toContain('nested: {')
    expect(output).toContain('deeply: {')
    expect(output).toContain('values: string[]')
    expect(output).toContain('method(): void')

    // Should NOT include example code from separate block
    expect(output).not.toContain('const example')

    await cleanupTestEnv(testDir)
  })

  test('filtering: mixed exports and non-exports', async () => {
    const testDir = await setupTestEnv({
      'mixed.md': `# Mixed types

Type definitions:
\`\`\`typescript
// Helper constant used by exported function
const HELPER = 'value'

export type Public = {
  value: string
}

export function guard(x: unknown): x is Public {
  return typeof x === 'object'
}
\`\`\`

Usage example (separate block):
\`\`\`typescript
// This entire block should be excluded
const x: Public = { value: 'test' }

if (guard(x)) {
  console.log(x.value)
}
\`\`\``,
    })

    const result = await runExtraction(testDir)
    expect(result.exitCode).toBe(0)

    const output = await Bun.file(join(testDir, 'types', 'mixed.ts')).text()

    // Should include exports AND dependencies in the same block
    expect(output).toContain('const HELPER')
    expect(output).toContain('export type Public')
    expect(output).toContain('export function guard')

    // Should NOT include example code from separate block
    expect(output).not.toContain('const x:')
    expect(output).not.toContain('if (guard(x))')
    expect(output).not.toContain('console.log')

    await cleanupTestEnv(testDir)
  })

  test('filtering: multi-line union types are preserved', async () => {
    const testDir = await setupTestEnv({
      'unions.md': `# Unions

Type definitions:
\`\`\`typescript
export type Status =
  | "pending"
  | "active"
  | "completed"

export type Result<T> =
  | { ok: true; value: T }
  | { ok: false; error: string }
\`\`\`

Usage example:
\`\`\`typescript
const example: Status = "pending"
\`\`\``,
    })

    const result = await runExtraction(testDir)
    expect(result.exitCode).toBe(0)

    const output = await Bun.file(join(testDir, 'types', 'unions.ts')).text()

    // Should include complete union types
    expect(output).toContain('export type Status')
    expect(output).toContain('| "pending"')
    expect(output).toContain('| "active"')
    expect(output).toContain('| "completed"')

    expect(output).toContain('export type Result<T>')
    expect(output).toContain('| { ok: true; value: T }')
    expect(output).toContain('| { ok: false; error: string }')

    // Should NOT include example from separate block
    expect(output).not.toContain('const example')

    await cleanupTestEnv(testDir)
  })

  test('filtering: const dependencies of exported functions are preserved', async () => {
    const testDir = await setupTestEnv({
      'authz.md': `# Authorization

Access hierarchy and helper:
\`\`\`typescript
export type AccessLevel = "owner" | "write" | "read"

const ACCESS_HIERARCHY: Record<AccessLevel, number> = {
  owner: 3,
  write: 2,
  read: 1,
}

export function hasAccess(
  userLevel: AccessLevel,
  requiredLevel: AccessLevel
): boolean {
  return ACCESS_HIERARCHY[userLevel] >= ACCESS_HIERARCHY[requiredLevel]
}
\`\`\``,
    })

    const result = await runExtraction(testDir)
    expect(result.exitCode).toBe(0)

    const output = await Bun.file(join(testDir, 'types', 'authz.ts')).text()

    // Should include the type
    expect(output).toContain('export type AccessLevel')

    // Should include the const (dependency of exported function)
    expect(output).toContain('const ACCESS_HIERARCHY')
    expect(output).toContain('owner: 3')

    // Should include the exported function
    expect(output).toContain('export function hasAccess')
    expect(output).toContain('ACCESS_HIERARCHY[userLevel]')

    await cleanupTestEnv(testDir)
  })

  test('filtering: code block with only non-exported code produces no output', async () => {
    const testDir = await setupTestEnv({
      'examples.md': `# Examples

\`\`\`typescript
// Only example code, no exports
const foo = 'bar'
console.log(foo)
\`\`\`
`,
      'valid.md': `\`\`\`typescript
export type Valid = { ok: true }
\`\`\``,
    })

    const result = await runExtraction(testDir)
    expect(result.exitCode).toBe(0)

    // examples.ts should not exist (no exports found)
    const examplesExists = await Bun.file(join(testDir, 'types', 'examples.ts')).exists()
    expect(examplesExists).toBe(false)

    // valid.ts should exist
    const validOutput = await Bun.file(join(testDir, 'types', 'valid.ts')).text()
    expect(validOutput).toContain('export type Valid')

    await cleanupTestEnv(testDir)
  })

  test('regression: configuration-style usage examples are filtered out', async () => {
    const testDir = await setupTestEnv({
      'config.md': `# Configuration

Type definition:
\`\`\`typescript
export type Config = {
  port: number
  host: string
}
\`\`\`

Usage example:
\`\`\`typescript
import { config } from '@/config'

const server = Bun.serve({
  port: config.port,
  hostname: config.host,
  fetch: handler,
})

console.log(\`Server listening on \${config.host}:\${config.port}\`)
\`\`\`

Another example:
\`\`\`typescript
if (isDevelopment()) {
  console.log('Dev mode')
}
\`\`\``,
    })

    const result = await runExtraction(testDir)
    expect(result.exitCode).toBe(0)

    const output = await Bun.file(join(testDir, 'types', 'config.ts')).text()

    // Should include the type
    expect(output).toContain('export type Config')
    expect(output).toContain('port: number')

    // Should NOT include any usage examples
    expect(output).not.toContain('import {')
    expect(output).not.toContain('Bun.serve')
    expect(output).not.toContain('const server')
    expect(output).not.toContain('console.log')
    expect(output).not.toContain('isDevelopment()')
    expect(output).not.toContain('Dev mode')

    await cleanupTestEnv(testDir)
  })
})
