import { describe, test, expect } from 'bun:test'
import { join } from 'path'

const TEST_DIR = join(import.meta.dir, '__test_domains')
const EXTRACT_SCRIPT = join(import.meta.dir, 'extract-types.ts')

/**
 * Run the extraction script in a test directory
 */
async function runExtraction(testDir: string): Promise<{ stdout: string; stderr: string; exitCode: number }> {
  const proc = Bun.spawn(['bun', 'run', EXTRACT_SCRIPT], {
    cwd: testDir,
    env: { ...Bun.env, DOMAINS_DIR: testDir },
    stdout: 'pipe',
    stderr: 'pipe',
  })

  const [stdout, stderr] = await Promise.all([
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
  ])

  const exitCode = await proc.exited

  return { stdout, stderr, exitCode }
}

/**
 * Create a test environment with domain markdown files
 */
async function setupTestEnv(files: Record<string, string>): Promise<string> {
  const testDir = `${TEST_DIR}_${Date.now()}`
  const scriptsDir = join(testDir, 'scripts')

  // Create directories using mkdir command
  const mkdirProc = Bun.spawn(['mkdir', '-p', scriptsDir], {
    stdout: 'pipe',
    stderr: 'pipe',
  })
  await mkdirProc.exited

  // Copy extraction script to test directory
  const scriptContent = await Bun.file(EXTRACT_SCRIPT).text()
  await Bun.write(join(testDir, 'scripts', 'extract-types.ts'), scriptContent)

  // Write test markdown files
  for (const [filename, content] of Object.entries(files)) {
    await Bun.write(join(testDir, filename), content)
  }

  return testDir
}

/**
 * Clean up test environment
 */
async function cleanupTestEnv(testDir: string) {
  const proc = Bun.spawn(['rm', '-rf', testDir], {
    stdout: 'pipe',
    stderr: 'pipe',
  })
  await proc.exited
}

describe('extract-types script', () => {
  test('basic extraction: single type in one file', async () => {
    const testDir = await setupTestEnv({
      'test.md': `# Test Domain

\`\`\`typescript
export type TestType = {
  id: string
  name: string
}
\`\`\`
`,
    })

    const result = await runExtraction(testDir)
    expect(result.exitCode).toBe(0)

    const output = await Bun.file(join(testDir, 'types', 'test.ts')).text()
    expect(output).toContain('export type TestType')
    expect(output).toContain('id: string')
    expect(output).toContain('name: string')
    expect(output).toContain('DO NOT EDIT THIS FILE DIRECTLY')
    expect(output).toContain('domains/test.md')

    await cleanupTestEnv(testDir)
  })

  test('multiple code blocks: combines into single namespace', async () => {
    const testDir = await setupTestEnv({
      'domain.md': `# Domain

First type:
\`\`\`typescript
export type TypeA = { a: string }
\`\`\`

Second type:
\`\`\`typescript
export type TypeB = { b: number }
\`\`\`
`,
    })

    const result = await runExtraction(testDir)
    expect(result.exitCode).toBe(0)

    const output = await Bun.file(join(testDir, 'types', 'domain.ts')).text()
    expect(output).toContain('export type TypeA')
    expect(output).toContain('export type TypeB')

    await cleanupTestEnv(testDir)
  })

  test('file generation: multiple domains create separate files', async () => {
    const testDir = await setupTestEnv({
      'auth.md': `\`\`\`typescript
export type User = { id: string }
\`\`\``,
      'books.md': `\`\`\`typescript
export type Book = { title: string }
\`\`\``,
    })

    const result = await runExtraction(testDir)
    expect(result.exitCode).toBe(0)

    const authOutput = await Bun.file(join(testDir, 'types', 'auth.ts')).text()
    expect(authOutput).toContain('export type User')

    const booksOutput = await Bun.file(join(testDir, 'types', 'books.ts')).text()
    expect(booksOutput).toContain('export type Book')

    await cleanupTestEnv(testDir)
  })

  test('export preservation: maintains all export types', async () => {
    const testDir = await setupTestEnv({
      'exports.md': `\`\`\`typescript
export type TypeA = string
export interface InterfaceB { x: number }
export enum EnumC { A, B, C }
export class ErrorD extends Error {}
export function guardE(x: unknown): x is TypeA { return typeof x === 'string' }
\`\`\``,
    })

    const result = await runExtraction(testDir)
    expect(result.exitCode).toBe(0)

    const output = await Bun.file(join(testDir, 'types', 'exports.ts')).text()
    expect(output).toContain('export type TypeA')
    expect(output).toContain('export interface InterfaceB')
    expect(output).toContain('export enum EnumC')
    expect(output).toContain('export class ErrorD')
    expect(output).toContain('export function guardE')

    await cleanupTestEnv(testDir)
  })

  test('idempotency: running twice produces identical output', async () => {
    const testDir = await setupTestEnv({
      'test.md': `\`\`\`typescript
export type Test = { value: number }
\`\`\``,
    })

    const result1 = await runExtraction(testDir)
    expect(result1.exitCode).toBe(0)
    const output1 = await Bun.file(join(testDir, 'types', 'test.ts')).text()

    const result2 = await runExtraction(testDir)
    expect(result2.exitCode).toBe(0)
    const output2 = await Bun.file(join(testDir, 'types', 'test.ts')).text()

    expect(output1).toBe(output2)

    await cleanupTestEnv(testDir)
  })

  test('edge case: file with no code blocks', async () => {
    const testDir = await setupTestEnv({
      'empty.md': `# Empty Domain

This has no TypeScript code blocks.
`,
      'valid.md': `\`\`\`typescript
export type Valid = { ok: true }
\`\`\``,
    })

    const result = await runExtraction(testDir)
    expect(result.exitCode).toBe(0) // Should still succeed

    // empty.ts should not exist
    const emptyExists = await Bun.file(join(testDir, 'types', 'empty.ts')).exists()
    expect(emptyExists).toBe(false)

    // valid.ts should exist
    const validOutput = await Bun.file(join(testDir, 'types', 'valid.ts')).text()
    expect(validOutput).toContain('export type Valid')

    await cleanupTestEnv(testDir)
  })

  test('edge case: README.md is excluded', async () => {
    const testDir = await setupTestEnv({
      'README.md': `\`\`\`typescript
export type ShouldNotAppear = { bad: true }
\`\`\``,
      'domain.md': `\`\`\`typescript
export type ShouldAppear = { good: true }
\`\`\``,
    })

    const result = await runExtraction(testDir)
    expect(result.exitCode).toBe(0)

    // README.ts should not exist
    const readmeExists = await Bun.file(join(testDir, 'types', 'README.ts')).exists()
    expect(readmeExists).toBe(false)

    // domain.ts should exist and contain the right type
    const domainOutput = await Bun.file(join(testDir, 'types', 'domain.ts')).text()
    expect(domainOutput).toContain('ShouldAppear')
    expect(domainOutput).not.toContain('ShouldNotAppear')

    await cleanupTestEnv(testDir)
  })

  test('caching: second run uses cache for unchanged files', async () => {
    const testDir = await setupTestEnv({
      'test.md': `\`\`\`typescript
export type Test = { cached: true }
\`\`\``,
    })

    // First run
    const result1 = await runExtraction(testDir)
    expect(result1.exitCode).toBe(0)
    expect(result1.stdout).toContain('extracting types')

    // Second run (should use cache)
    const result2 = await runExtraction(testDir)
    expect(result2.exitCode).toBe(0)
    expect(result2.stdout).toContain('using cached extraction')

    await cleanupTestEnv(testDir)
  })

  test('caching: detects file changes and re-extracts', async () => {
    const testDir = await setupTestEnv({
      'test.md': `\`\`\`typescript
export type Test = { version: 1 }
\`\`\``,
    })

    // First run
    const result1 = await runExtraction(testDir)
    expect(result1.exitCode).toBe(0)

    // Modify file
    await Bun.write(
      join(testDir, 'test.md'),
      `\`\`\`typescript
export type Test = { version: 2 }
\`\`\``
    )

    // Second run (should re-extract)
    const result2 = await runExtraction(testDir)
    expect(result2.exitCode).toBe(0)
    expect(result2.stdout).toContain('extracting types')

    const output = await Bun.file(join(testDir, 'types', 'test.ts')).text()
    expect(output).toContain('version: 2')

    await cleanupTestEnv(testDir)
  })

  test('error handling: exits with error code when no .md files found', async () => {
    const testDir = `${TEST_DIR}_${Date.now()}`
    const scriptsDir = join(testDir, 'scripts')

    // Create directories using mkdir command
    const mkdirProc = Bun.spawn(['mkdir', '-p', scriptsDir], {
      stdout: 'pipe',
      stderr: 'pipe',
    })
    await mkdirProc.exited

    const scriptContent = await Bun.file(EXTRACT_SCRIPT).text()
    await Bun.write(join(testDir, 'scripts', 'extract-types.ts'), scriptContent)

    const result = await runExtraction(testDir)
    expect(result.exitCode).toBe(0) // Script exits cleanly when no files found

    await cleanupTestEnv(testDir)
  })
})
