import { describe, test, expect, beforeAll, afterAll } from 'bun:test'
import { writeFile, readFile, mkdir, rm } from 'node:fs/promises'
import { join } from 'node:path'
import { spawn } from 'node:child_process'

const TEST_DIR = join(import.meta.dir, '__test_domains')
const EXTRACT_SCRIPT = join(import.meta.dir, 'extract-types.ts')

/**
 * Run the extraction script in a test directory
 */
async function runExtraction(testDir: string): Promise<{ stdout: string; stderr: string; exitCode: number }> {
  return new Promise((resolve, reject) => {
    const proc = spawn('bun', ['run', EXTRACT_SCRIPT], {
      cwd: testDir,
      env: { ...process.env, DOMAINS_DIR: testDir },
    })

    let stdout = ''
    let stderr = ''

    proc.stdout.on('data', (data) => {
      stdout += data.toString()
    })

    proc.stderr.on('data', (data) => {
      stderr += data.toString()
    })

    proc.on('close', (code) => {
      resolve({ stdout, stderr, exitCode: code || 0 })
    })

    proc.on('error', reject)
  })
}

/**
 * Create a test environment with domain markdown files
 */
async function setupTestEnv(files: Record<string, string>): Promise<string> {
  const testDir = `${TEST_DIR}_${Date.now()}`
  await mkdir(join(testDir, 'scripts'), { recursive: true })

  // Copy extraction script to test directory
  const scriptContent = await readFile(EXTRACT_SCRIPT, 'utf-8')
  await writeFile(join(testDir, 'scripts', 'extract-types.ts'), scriptContent, 'utf-8')

  // Write test markdown files
  for (const [filename, content] of Object.entries(files)) {
    await writeFile(join(testDir, filename), content, 'utf-8')
  }

  return testDir
}

/**
 * Clean up test environment
 */
async function cleanupTestEnv(testDir: string) {
  await rm(testDir, { recursive: true, force: true })
}

describe('extract-types script', () => {
  test('basic extraction: single type in one file', async () => {
    const testDir = await setupTestEnv({
      'test.md': `# Test Domain

\`\`\`typescript
export type TestType = {
  id: string
  name: string
}
\`\`\`
`,
    })

    const result = await runExtraction(testDir)
    expect(result.exitCode).toBe(0)

    const output = await readFile(join(testDir, 'types', 'test.ts'), 'utf-8')
    expect(output).toContain('export type TestType')
    expect(output).toContain('id: string')
    expect(output).toContain('name: string')
    expect(output).toContain('DO NOT EDIT THIS FILE DIRECTLY')
    expect(output).toContain('domains/test.md')

    await cleanupTestEnv(testDir)
  })

  test('multiple code blocks: combines into single namespace', async () => {
    const testDir = await setupTestEnv({
      'domain.md': `# Domain

First type:
\`\`\`typescript
export type TypeA = { a: string }
\`\`\`

Second type:
\`\`\`typescript
export type TypeB = { b: number }
\`\`\`
`,
    })

    const result = await runExtraction(testDir)
    expect(result.exitCode).toBe(0)

    const output = await readFile(join(testDir, 'types', 'domain.ts'), 'utf-8')
    expect(output).toContain('export type TypeA')
    expect(output).toContain('export type TypeB')

    await cleanupTestEnv(testDir)
  })

  test('file generation: multiple domains create separate files', async () => {
    const testDir = await setupTestEnv({
      'auth.md': `\`\`\`typescript
export type User = { id: string }
\`\`\``,
      'books.md': `\`\`\`typescript
export type Book = { title: string }
\`\`\``,
    })

    const result = await runExtraction(testDir)
    expect(result.exitCode).toBe(0)

    const authOutput = await readFile(join(testDir, 'types', 'auth.ts'), 'utf-8')
    expect(authOutput).toContain('export type User')

    const booksOutput = await readFile(join(testDir, 'types', 'books.ts'), 'utf-8')
    expect(booksOutput).toContain('export type Book')

    await cleanupTestEnv(testDir)
  })

  test('export preservation: maintains all export types', async () => {
    const testDir = await setupTestEnv({
      'exports.md': `\`\`\`typescript
export type TypeA = string
export interface InterfaceB { x: number }
export enum EnumC { A, B, C }
export class ErrorD extends Error {}
export function guardE(x: unknown): x is TypeA { return typeof x === 'string' }
\`\`\``,
    })

    const result = await runExtraction(testDir)
    expect(result.exitCode).toBe(0)

    const output = await readFile(join(testDir, 'types', 'exports.ts'), 'utf-8')
    expect(output).toContain('export type TypeA')
    expect(output).toContain('export interface InterfaceB')
    expect(output).toContain('export enum EnumC')
    expect(output).toContain('export class ErrorD')
    expect(output).toContain('export function guardE')

    await cleanupTestEnv(testDir)
  })

  test('idempotency: running twice produces identical output', async () => {
    const testDir = await setupTestEnv({
      'test.md': `\`\`\`typescript
export type Test = { value: number }
\`\`\``,
    })

    const result1 = await runExtraction(testDir)
    expect(result1.exitCode).toBe(0)
    const output1 = await readFile(join(testDir, 'types', 'test.ts'), 'utf-8')

    const result2 = await runExtraction(testDir)
    expect(result2.exitCode).toBe(0)
    const output2 = await readFile(join(testDir, 'types', 'test.ts'), 'utf-8')

    expect(output1).toBe(output2)

    await cleanupTestEnv(testDir)
  })

  test('edge case: file with no code blocks', async () => {
    const testDir = await setupTestEnv({
      'empty.md': `# Empty Domain

This has no TypeScript code blocks.
`,
      'valid.md': `\`\`\`typescript
export type Valid = { ok: true }
\`\`\``,
    })

    const result = await runExtraction(testDir)
    expect(result.exitCode).toBe(0) // Should still succeed

    const { access } = await import('node:fs/promises')
    // empty.ts should not exist
    await expect(access(join(testDir, 'types', 'empty.ts'))).rejects.toThrow()

    // valid.ts should exist
    const validOutput = await readFile(join(testDir, 'types', 'valid.ts'), 'utf-8')
    expect(validOutput).toContain('export type Valid')

    await cleanupTestEnv(testDir)
  })

  test('edge case: README.md is excluded', async () => {
    const testDir = await setupTestEnv({
      'README.md': `\`\`\`typescript
export type ShouldNotAppear = { bad: true }
\`\`\``,
      'domain.md': `\`\`\`typescript
export type ShouldAppear = { good: true }
\`\`\``,
    })

    const result = await runExtraction(testDir)
    expect(result.exitCode).toBe(0)

    const { access } = await import('node:fs/promises')
    // README.ts should not exist
    await expect(access(join(testDir, 'types', 'README.ts'))).rejects.toThrow()

    // domain.ts should exist and contain the right type
    const domainOutput = await readFile(join(testDir, 'types', 'domain.ts'), 'utf-8')
    expect(domainOutput).toContain('ShouldAppear')
    expect(domainOutput).not.toContain('ShouldNotAppear')

    await cleanupTestEnv(testDir)
  })

  test('caching: second run uses cache for unchanged files', async () => {
    const testDir = await setupTestEnv({
      'test.md': `\`\`\`typescript
export type Test = { cached: true }
\`\`\``,
    })

    // First run
    const result1 = await runExtraction(testDir)
    expect(result1.exitCode).toBe(0)
    expect(result1.stdout).toContain('extracting types')

    // Second run (should use cache)
    const result2 = await runExtraction(testDir)
    expect(result2.exitCode).toBe(0)
    expect(result2.stdout).toContain('using cached extraction')

    await cleanupTestEnv(testDir)
  })

  test('caching: detects file changes and re-extracts', async () => {
    const testDir = await setupTestEnv({
      'test.md': `\`\`\`typescript
export type Test = { version: 1 }
\`\`\``,
    })

    // First run
    const result1 = await runExtraction(testDir)
    expect(result1.exitCode).toBe(0)

    // Modify file
    await writeFile(
      join(testDir, 'test.md'),
      `\`\`\`typescript
export type Test = { version: 2 }
\`\`\``,
      'utf-8'
    )

    // Second run (should re-extract)
    const result2 = await runExtraction(testDir)
    expect(result2.exitCode).toBe(0)
    expect(result2.stdout).toContain('extracting types')

    const output = await readFile(join(testDir, 'types', 'test.ts'), 'utf-8')
    expect(output).toContain('version: 2')

    await cleanupTestEnv(testDir)
  })

  test('error handling: exits with error code when no .md files found', async () => {
    const testDir = `${TEST_DIR}_${Date.now()}`
    await mkdir(join(testDir, 'scripts'), { recursive: true })

    const scriptContent = await readFile(EXTRACT_SCRIPT, 'utf-8')
    await writeFile(join(testDir, 'scripts', 'extract-types.ts'), scriptContent, 'utf-8')

    const result = await runExtraction(testDir)
    expect(result.exitCode).toBe(0) // Script exits cleanly when no files found

    await cleanupTestEnv(testDir)
  })
})
