#!/usr/bin/env bun

/**
 * Extract TypeScript code blocks from domain markdown files and generate types.ts
 *
 * This script:
 * 1. Scans /domains for .md files (excluding README.md)
 * 2. Extracts all TypeScript code blocks from each file
 * 3. Groups types by domain into namespaces
 * 4. Generates domains/types.ts with all extracted types
 */

import { readdir, readFile, writeFile } from 'node:fs/promises'
import { join, basename } from 'node:path'
import { createHash } from 'node:crypto'

// Allow override for testing, otherwise default to parent of script directory
const DOMAINS_DIR = process.env.DOMAINS_DIR || join(import.meta.dir, '..')
const OUTPUT_DIR = join(DOMAINS_DIR, 'types')
const CACHE_FILE = join(DOMAINS_DIR, '.domains-cache.json')

interface CacheEntry {
  hash: string
  extracted: string
}

type Cache = Record<string, CacheEntry>

/**
 * Calculate SHA-256 hash of file content
 */
function hashContent(content: string): string {
  return createHash('sha256').update(content).digest('hex')
}

/**
 * Load cache from disk
 */
async function loadCache(): Promise<Cache> {
  try {
    const content = await readFile(CACHE_FILE, 'utf-8')
    return JSON.parse(content)
  } catch {
    return {}
  }
}

/**
 * Save cache to disk
 */
async function saveCache(cache: Cache): Promise<void> {
  await writeFile(CACHE_FILE, JSON.stringify(cache, null, 2), 'utf-8')
}

/**
 * Extract TypeScript code blocks from markdown content
 */
function extractTypeScriptBlocks(markdown: string): string {
  const codeBlockRegex = /```typescript\n([\s\S]*?)```/g
  const blocks: string[] = []

  let match
  while ((match = codeBlockRegex.exec(markdown)) !== null) {
    blocks.push(match[1].trim())
  }

  return blocks.join('\n\n')
}

/**
 * Get domain name from filename (e.g., "books.md" -> "books")
 */
function getDomainName(filename: string): string {
  return basename(filename, '.md')
}

/**
 * Find all .md files in domains directory (excluding README.md)
 */
async function findDomainFiles(): Promise<string[]> {
  const entries = await readdir(DOMAINS_DIR, { withFileTypes: true })
  return entries
    .filter((entry) => entry.isFile() && entry.name.endsWith('.md') && entry.name !== 'README.md')
    .map((entry) => entry.name)
}

/**
 * Generate the header comment for individual type files
 */
function generateHeader(domainName: string): string {
  return `/**
 * Auto-generated from domains/${domainName}.md
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * This file is automatically generated by domains/scripts/extract-types.ts
 * which extracts TypeScript code blocks from the markdown domain documentation.
 *
 * To make changes:
 * 1. Edit the corresponding .md file in /domains
 * 2. Run: bun run domains/scripts/extract-types.ts
 * 3. Or commit changes - the pre-commit hook will regenerate automatically
 */

`
}

/**
 * Main extraction logic
 */
async function main() {
  try {
    console.log('Loading cache...')
    const cache = await loadCache()

    console.log('Finding domain files...')
    const domainFiles = await findDomainFiles()

    if (domainFiles.length === 0) {
      console.warn('No domain .md files found in /domains')
      process.exit(0)
    }

    console.log(`Found ${domainFiles.length} domain files:`, domainFiles.join(', '))

    // Ensure output directory exists
    const { mkdir } = await import('node:fs/promises')
    await mkdir(OUTPUT_DIR, { recursive: true })

    const newCache: Cache = {}
    const generatedFiles: string[] = []

    for (const filename of domainFiles) {
      const filePath = join(DOMAINS_DIR, filename)
      const content = await readFile(filePath, 'utf-8')
      const hash = hashContent(content)

      // Check cache
      const cached = cache[filename]
      let extractedTypes: string

      if (cached && cached.hash === hash) {
        console.log(`  ${filename}: using cached extraction`)
        extractedTypes = cached.extracted
      } else {
        console.log(`  ${filename}: extracting types...`)
        extractedTypes = extractTypeScriptBlocks(content)

        if (!extractedTypes) {
          console.warn(`  ${filename}: no TypeScript code blocks found`)
          continue
        }
      }

      const domainName = getDomainName(filename)
      const outputFile = join(OUTPUT_DIR, `${domainName}.ts`)

      // Generate file content
      const output = generateHeader(domainName) + extractedTypes

      await writeFile(outputFile, output, 'utf-8')
      generatedFiles.push(outputFile)

      // Update cache
      newCache[filename] = { hash, extracted: extractedTypes }
    }

    if (generatedFiles.length === 0) {
      console.error('No TypeScript code blocks extracted from any domain files')
      process.exit(1)
    }

    console.log(`✓ Generated ${generatedFiles.length} type files in ${OUTPUT_DIR}`)

    console.log('Saving cache...')
    await saveCache(newCache)

    console.log('✓ Done!')
  } catch (error) {
    console.error('Error during extraction:', error)
    process.exit(1)
  }
}

main()
