/opt/quailcomp/logs/*.log {
    daily
    rotate 14
    compress
    delaycompress
    missingok
    notifempty
    create 0640 quailcomp quailcomp
    sharedscripts
    postrotate
        systemctl reload quailcomp > /dev/null 2>&1 || true
    endscript
}
