/**
 * Extract TypeScript code blocks from domain markdown files and generate types
 *
 * Adapted from domains/scripts/extract-types.ts to work as a watch task
 */

import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises'
import { join, basename } from 'node:path'
import { createHash } from 'node:crypto'
import type { TaskResult } from '../types'

// Project root is 2 levels up from this file
const PROJECT_ROOT = join(import.meta.dir, '../../..')
const DOMAINS_DIR = join(PROJECT_ROOT, 'domains')
const OUTPUT_DIR = join(DOMAINS_DIR, 'types')
const CACHE_FILE = join(DOMAINS_DIR, '.domains-cache.json')

interface CacheEntry {
  hash: string
  extracted: string
}

type Cache = Record<string, CacheEntry>

/**
 * Calculate SHA-256 hash of file content
 */
function hashContent(content: string): string {
  return createHash('sha256').update(content).digest('hex')
}

/**
 * Load cache from disk
 */
async function loadCache(): Promise<Cache> {
  try {
    const content = await readFile(CACHE_FILE, 'utf-8')
    return JSON.parse(content)
  } catch {
    return {}
  }
}

/**
 * Save cache to disk
 */
async function saveCache(cache: Cache): Promise<void> {
  await writeFile(CACHE_FILE, JSON.stringify(cache, null, 2), 'utf-8')
}

/**
 * Extract TypeScript code blocks from markdown content
 */
function extractTypeScriptBlocks(markdown: string): string {
  const codeBlockRegex = /```typescript\n([\s\S]*?)```/g
  const blocks: string[] = []

  let match
  while ((match = codeBlockRegex.exec(markdown)) !== null) {
    blocks.push(match[1].trim())
  }

  return blocks.join('\n\n')
}

/**
 * Get domain name from filename (e.g., "books.md" -> "books")
 */
function getDomainName(filename: string): string {
  return basename(filename, '.md')
}

/**
 * Find all .md files in domains directory (excluding README.md)
 */
async function findDomainFiles(): Promise<string[]> {
  const entries = await readdir(DOMAINS_DIR, { withFileTypes: true })
  return entries
    .filter((entry) => entry.isFile() && entry.name.endsWith('.md') && entry.name !== 'README.md')
    .map((entry) => entry.name)
}

/**
 * Generate the header comment for individual type files
 */
function generateHeader(domainName: string): string {
  return `/**
 * Auto-generated from domains/${domainName}.md
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * This file is automatically generated by devtools/watch/tasks/types-from-docs.ts
 * which extracts TypeScript code blocks from the markdown domain documentation.
 *
 * To make changes:
 * 1. Edit the corresponding .md file in /domains
 * 2. The devtools watcher will regenerate automatically
 * 3. Or run manually: bun run devtools/watch/tasks/types-from-docs.ts
 */

`
}

/**
 * Main extraction logic (adapted for watch task)
 */
export async function extractTypes(changed: string[]): Promise<TaskResult> {
  const startTime = Date.now()
  const output: string[] = []
  const errors: string[] = []

  try {
    output.push('Loading cache...')
    const cache = await loadCache()

    output.push('Finding domain files...')
    const domainFiles = await findDomainFiles()

    if (domainFiles.length === 0) {
      output.push('⚠ No domain .md files found in /domains')
      return {
        success: true,
        stdout: output.join('\n'),
        stderr: '',
        duration: Date.now() - startTime,
      }
    }

    output.push(`Found ${domainFiles.length} domain files: ${domainFiles.join(', ')}`)

    // Ensure output directory exists
    await mkdir(OUTPUT_DIR, { recursive: true })

    const newCache: Cache = {}
    const generatedFiles: string[] = []

    for (const filename of domainFiles) {
      const filePath = join(DOMAINS_DIR, filename)
      const content = await readFile(filePath, 'utf-8')
      const hash = hashContent(content)

      // Check cache
      const cached = cache[filename]
      let extractedTypes: string

      if (cached && cached.hash === hash) {
        output.push(`  ${filename}: using cached extraction`)
        extractedTypes = cached.extracted
      } else {
        output.push(`  ${filename}: extracting types...`)
        extractedTypes = extractTypeScriptBlocks(content)

        if (!extractedTypes) {
          output.push(`  ${filename}: ⚠ no TypeScript code blocks found`)
          continue
        }
      }

      const domainName = getDomainName(filename)
      const outputFile = join(OUTPUT_DIR, `${domainName}.ts`)

      // Generate file content
      const fileContent = generateHeader(domainName) + extractedTypes + '\n'

      await writeFile(outputFile, fileContent, 'utf-8')
      generatedFiles.push(outputFile)

      // Update cache
      newCache[filename] = { hash, extracted: extractedTypes }
    }

    if (generatedFiles.length === 0) {
      errors.push('❌ No TypeScript code blocks extracted from any domain files')
      return {
        success: false,
        stdout: output.join('\n'),
        stderr: errors.join('\n'),
        duration: Date.now() - startTime,
      }
    }

    output.push(`✓ Generated ${generatedFiles.length} type files in ${OUTPUT_DIR}`)

    output.push('Saving cache...')
    await saveCache(newCache)

    output.push('✓ Done!')

    return {
      success: true,
      stdout: output.join('\n'),
      stderr: '',
      duration: Date.now() - startTime,
    }
  } catch (error) {
    errors.push(`❌ Error during extraction: ${error}`)
    return {
      success: false,
      stdout: output.join('\n'),
      stderr: errors.join('\n'),
      duration: Date.now() - startTime,
      error: error as Error,
    }
  }
}

// Allow running standalone for testing
if (import.meta.main) {
  const result = await extractTypes([])
  console.log(result.stdout)
  if (result.stderr) {
    console.error(result.stderr)
  }
  process.exit(result.success ? 0 : 1)
}
