/**
 * Auto-generated from domains/analytics.md
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * This file is automatically generated by devtools/watch/tasks/types-from-docs.ts
 * which extracts TypeScript code blocks from the markdown domain documentation.
 *
 * To make changes:
 * 1. Edit the corresponding .md file in /domains
 * 2. The devtools watcher will regenerate automatically
 * 3. Or run manually: bun run devtools/watch/tasks/types-from-docs.ts
 */

export type HttpRequestEvent = {
  request_id: string;
  method: string;
  path: string; // Normalized: /api/books/{id}
  status_code: number;
  duration_ms: number;
  user_id: number | null;
  user_agent?: string;
};

export type HttpErrorEvent = {
  request_id: string;
  method: string;
  path: string;
  error_message: string;
  error_stack?: string;
  error_code?: string;
  user_id: number | null;
};

export type MetadataProviderResult = {
  name: string;
  success: boolean;
  duration_ms: number;
  error_message?: string;
};

export type MetadataLookupEvent = {
  request_id: string;
  identifier: string;
  identifier_type: 'isbn' | 'lccn' | 'oclc' | 'title';
  providers: MetadataProviderResult[];
  results_count: number;
  user_id: number | null;
};

export type UserSessionStartedEvent = {
  user_id: number;
  session_id: string;
  auth_method: 'password' | 'passkey' | 'oauth_google' | 'oauth_github' | 'api_key';
  request_id: string;
};

export type UserSessionEndedEvent = {
  user_id: number;
  session_id: string;
  duration_seconds: number;
  request_id: string;
};

export type UserMilestoneEvent = {
  user_id: number;
  milestone:
    | 'registration'
    | 'first_book_added'
    | 'first_metadata_lookup'
    | 'first_book_deleted'
    | 'collection_size_10'
    | 'collection_size_50'
    | 'collection_size_100';
  auth_method?: string;
  request_id: string;
  metadata?: Record<string, unknown>;
  days_since_registration?: number;
};

export type FeatureUsageEvent = {
  user_id: number | null;
  feature: string;
  action: string;
  request_id: string;
  metadata?: Record<string, unknown>;
};

// Get all HTTP requests from the last 7 days
const recentRequests = await events.getByTimeRange(
  new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
  new Date()
);
const httpRequests = recentRequests.filter(
  e => e.eventType === 'analytics.http_request' && !e.voidedAt
);

// Count unique users who logged in each day
const loginEvents = await events.getByType('analytics.user_session_started');
const dau = new Map<string, Set<number>>();

for (const event of loginEvents) {
  const date = event.occurredAt.toISOString().split('T')[0];
  const userId = (event.data as UserSessionStartedEvent).user_id;
  if (!dau.has(date)) dau.set(date, new Set());
  dau.get(date)!.add(userId);
}

const dailyCounts = new Map(
  [...dau].map(([date, users]) => [date, users.size])
);

// Calculate p50, p95, p99 latencies for an endpoint
const requests = await events.findByData('analytics.http_request', {
  path: '/api/books'
});

const durations = requests
  .map(e => (e.data as HttpRequestEvent).duration_ms)
  .sort((a, b) => a - b);

const p50 = durations[Math.floor(durations.length * 0.50)];
const p95 = durations[Math.floor(durations.length * 0.95)];
const p99 = durations[Math.floor(durations.length * 0.99)];
