/**
 * Auto-generated from domains/authentication.md
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * This file is automatically generated by domains/scripts/extract-types.ts
 * which extracts TypeScript code blocks from the markdown domain documentation.
 *
 * To make changes:
 * 1. Edit the corresponding .md file in /domains
 * 2. Run: bun run domains/scripts/extract-types.ts
 * 3. Or commit changes - the pre-commit hook will regenerate automatically
 */

export interface User {
  userId: number
  username: string | null
  email: string
  createdAt: Date
  updatedAt: Date
}

export type CredentialType =
  | "password"
  | "passkey"
  | "oauth_google"
  | "oauth_github"
  | "api_key"

export interface Credential {
  credentialId: number
  userId: number
  credentialType: CredentialType
  credentialData: CredentialData
  createdAt: Date
  lastUsedAt: Date | null
  isActive: boolean
}

export interface PasswordCredentialData {
  identifier: string
  password_hash: string
}

export interface PasskeyCredentialData {
  credential_id: string
  public_key: string
  counter: number
  device_name?: string
  aaguid?: string
  transports?: ("usb" | "nfc" | "ble" | "internal")[]
}

export interface OAuthCredentialData {
  provider_user_id: string
  email: string
  profile?: {
    name?: string
    avatar_url?: string
    locale?: string
    [key: string]: unknown
  }
  access_token_hash?: string
  refresh_token_hash?: string
  token_expires_at?: string
}

export interface ApiKeyCredentialData {
  key_hash: string
  prefix: string
  last_4: string
  name?: string
  scopes?: string[]
  ip_whitelist?: string[]
  rate_limit?: number
}

export type CredentialData =
  | PasswordCredentialData
  | PasskeyCredentialData
  | OAuthCredentialData
  | ApiKeyCredentialData

export interface JWTPayload {
  user_id: number
  email: string
  username?: string
  iat: number
  exp: number
  credential_id?: number
  auth_method?: CredentialType
  session_id?: string
}

export interface RegisterRequest {
  email: string
  username?: string
  password: string
}

export interface LoginRequest {
  identifier: string
  password: string
}

export interface AuthResponse {
  user: {
    userId: number
    email: string
    username: string | null
  }
  token: string
  expiresAt: string
}

export type AuthErrorCode =
  | "EMAIL_EXISTS"
  | "USERNAME_EXISTS"
  | "INVALID_CREDENTIALS"
  | "PASSWORD_TOO_SHORT"
  | "PASSWORD_TOO_WEAK"
  | "INVALID_EMAIL"
  | "USER_NOT_FOUND"
  | "CREDENTIAL_INACTIVE"
export class AuthError extends Error {
  constructor(
    message: string,
    public code: AuthErrorCode
  ) {
    super(message)
    this.name = "AuthError"
  }
}

export interface UserRow {
  user_id: number
  username: string | null
  email: string
  created_at: Date
  updated_at: Date
}

export interface CredentialRow {
  credential_id: number
  user_id: number
  credential_type: CredentialType
  credential_data: CredentialData
  created_at: Date
  last_used_at: Date | null
  is_active: boolean
}

export function isPasswordCredential(data: CredentialData): data is PasswordCredentialData {
  return "password_hash" in data && "identifier" in data
}
export function isPasskeyCredential(data: CredentialData): data is PasskeyCredentialData {
  return "credential_id" in data && "public_key" in data && "counter" in data
}
export function isOAuthCredential(data: CredentialData): data is OAuthCredentialData {
  return "provider_user_id" in data
}
export function isApiKeyCredential(data: CredentialData): data is ApiKeyCredentialData {
  return "key_hash" in data && "prefix" in data && "last_4" in data
}

export function getCredentialDisplayName(credential: Credential): string {
  switch (credential.credentialType) {
    case "password": {
      const data = credential.credentialData as PasswordCredentialData
      return `Password (${data.identifier})`
    }
    case "passkey": {
      const data = credential.credentialData as PasskeyCredentialData
      return data.device_name ? `Passkey (${data.device_name})` : "Passkey"
    }
    case "oauth_google":
      return `Google (${(credential.credentialData as OAuthCredentialData).email})`
    case "oauth_github":
      return `GitHub (${(credential.credentialData as OAuthCredentialData).email})`
    case "api_key": {
      const data = credential.credentialData as ApiKeyCredentialData
      return data.name ? `API Key (${data.name})` : `API Key (${data.prefix}...${data.last_4})`
    }
  }
}

export function getCredentialTypeLabel(type: CredentialType): string {
  switch (type) {
    case "password":
      return "Password"
    case "passkey":
      return "Passkey"
    case "oauth_google":
      return "Google"
    case "oauth_github":
      return "GitHub"
    case "api_key":
      return "API Key"
  }
}
