/**
 * Auto-generated from domains/authorization.md
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * This file is automatically generated by devtools/watch/tasks/types-from-docs.ts
 * which extracts TypeScript code blocks from the markdown domain documentation.
 *
 * To make changes:
 * 1. Edit the corresponding .md file in /domains
 * 2. The devtools watcher will regenerate automatically
 * 3. Or run manually: bun run devtools/watch/tasks/types-from-docs.ts
 */

export type AccessLevel = "owner" | "write" | "read"

export interface EntityAccess {
  entityId: number
  userId: number
  accessLevel: AccessLevel
  grantedAt: Date
  grantedBy: number | null
}

export type AuthzErrorCode =
  | "ACCESS_DENIED"
  | "NOT_OWNER"
  | "CANNOT_REVOKE_SELF"
  | "ENTITY_NOT_FOUND"
export class AuthorizationError extends Error {
  constructor(
    message: string,
    public code: AuthzErrorCode
  ) {
    super(message)
    this.name = "AuthorizationError"
  }
}

export interface EntityAccessRow {
  entity_id: number
  user_id: number
  access_level: AccessLevel
  granted_at: Date
  granted_by: number | null
}

export interface EntityWithAccess {
  entityId: number
  entityType: string
  data: unknown
  accessLevel: AccessLevel
}

export interface AccessListItem {
  userId: number
  email: string
  username: string | null
  accessLevel: AccessLevel
  grantedAt: Date
  grantedBy: number | null
}
