/**
 * Auto-generated from domains/authorization.md
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * This file is automatically generated by domains/scripts/extract-types.ts
 * which extracts TypeScript code blocks from the markdown domain documentation.
 *
 * To make changes:
 * 1. Edit the corresponding .md file in /domains
 * 2. Run: bun run domains/scripts/extract-types.ts
 * 3. Or commit changes - the pre-commit hook will regenerate automatically
 */

export type AccessLevel = "owner" | "write" | "read"

const ACCESS_HIERARCHY: Record<AccessLevel, number> = {
  owner: 3,
  write: 2,
  read: 1,
}

hasAccess('owner', 'read')  // true - owner can do anything
hasAccess('write', 'owner') // false - write cannot do owner actions
hasAccess('read', 'read')   // true - exact match
hasAccess('owner', 'write') // true - owner exceeds write requirement

export function hasAccess(
  userLevel: AccessLevel,
  requiredLevel: AccessLevel
): boolean {
  return ACCESS_HIERARCHY[userLevel] >= ACCESS_HIERARCHY[requiredLevel]
}

export interface EntityAccess {
  entityId: number
  userId: number
  accessLevel: AccessLevel
  grantedAt: Date
  grantedBy: number | null
}

export type AuthzErrorCode =
  | "ACCESS_DENIED"
  | "NOT_OWNER"
  | "CANNOT_REVOKE_SELF"
  | "ENTITY_NOT_FOUND"

export class AuthorizationError extends Error {
  constructor(
    message: string,
    public code: AuthzErrorCode
  ) {
    super(message)
    this.name = "AuthorizationError"
  }
}

export interface EntityAccessRow {
  entity_id: number
  user_id: number
  access_level: AccessLevel
  granted_at: Date
  granted_by: number | null
}

export interface EntityWithAccess {
  entityId: number
  entityType: string
  data: unknown
  accessLevel: AccessLevel
}

export interface AccessListItem {
  userId: number
  email: string
  username: string | null
  accessLevel: AccessLevel
  grantedAt: Date
  grantedBy: number | null
}

export function getAccessLevelLabel(level: AccessLevel): string {
  switch (level) {
    case "owner":
      return "Owner"
    case "write":
      return "Can Edit"
    case "read":
      return "Can View"
  }
}

export function getAccessLevelDescription(level: AccessLevel): string {
  switch (level) {
    case "owner":
      return "Full control including deleting and managing access"
    case "write":
      return "Can view and modify but cannot delete or manage access"
    case "read":
      return "Can view only, cannot modify"
  }
}

export function getAccessLevelIcon(level: AccessLevel): string {
  switch (level) {
    case "owner":
      return "crown"
    case "write":
      return "edit"
    case "read":
      return "eye"
  }
}
