/**
 * Auto-generated from domains/books.md
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * This file is automatically generated by devtools/watch/tasks/types-from-docs.ts
 * which extracts TypeScript code blocks from the markdown domain documentation.
 *
 * To make changes:
 * 1. Edit the corresponding .md file in /domains
 * 2. The devtools watcher will regenerate automatically
 * 3. Or run manually: bun run devtools/watch/tasks/types-from-docs.ts
 */

export type PhysicalBook = {
  entity_id: string
  title?: string
  subtitle?: string
  author?: string
  series_id?: string
  isbn10?: string
  isbn13?: string
  lccn?: string
  note?: string
}

export type Money = {
  amount: number
  currency: string // e.g., "USD"
}

export type PurchasedAcquisition = {
  type: 'purchased'
  location_id: string
  cost: Money
  date: Date
  notes?: string
}

export type OrderedAcquisition = {
  type: 'ordered'
  cost: Money
  date: Date
  notes?: string
}

export type GivenAcquisition = {
  type: 'given'
  person_id: string
  date: Date
  notes?: string
}

export type WonAcquisition = {
  type: 'won'
  date: Date
  notes?: string
}

export type InheritedAcquisition = {
  type: 'inherited'
  date?: Date
  notes?: string
}

export type AcquisitionEvent =
  | PurchasedAcquisition
  | OrderedAcquisition
  | GivenAcquisition
  | WonAcquisition
  | InheritedAcquisition

export type LentEvent = {
  type: 'lent'
  person_id: string
  date: Date
  notes?: string
}

export type ReturnedEvent = {
  type: 'returned'
  date: Date
  notes?: string
}

export type DisposedEvent = {
  type: 'disposed'
  reason: 'destroyed' | 'given_away' | 'sold' | 'lost' | 'other'
  date: Date
  notes?: string
}

export type BookEvent =
  | AcquisitionEvent
  | LentEvent
  | ReturnedEvent
  | DisposedEvent

export type BookEntitySnapshot = {
  title?: string
  subtitle?: string
  author?: string
  series_id?: string
  isbn10?: string
  isbn13?: string
  lccn?: string
  note?: string
}

export type BookEntityRow = {
  entity_id: number
  entity_type: 'book'
  data: BookEntitySnapshot
  created_at: Date
  updated_at: Date
  deleted_at: Date | null
}

export type AcquisitionEventSnapshot = {
  type: 'purchased' | 'ordered' | 'given' | 'won' | 'inherited'
  location_id?: string
  person_id?: string
  cost?: {
    amount: number
    currency: string
  }
  date?: string // ISO date string
  notes?: string
}

export type AcquisitionEventRow = {
  entity_id: number
  entity_type: 'acquisition'
  data: AcquisitionEventSnapshot
  created_at: Date
  updated_at: Date
  deleted_at: Date | null
}

export type BookWithAcquisition = {
  book: PhysicalBook
  acquisition?: AcquisitionEvent
}

export type BookListItem = {
  entity_id: string
  title?: string
  subtitle?: string
  author?: string
  acquisition_date?: Date
}

export function isPurchased(acq: AcquisitionEvent): acq is PurchasedAcquisition {
  return acq.type === 'purchased'
}

export function isOrdered(acq: AcquisitionEvent): acq is OrderedAcquisition {
  return acq.type === 'ordered'
}

export function isGiven(acq: AcquisitionEvent): acq is GivenAcquisition {
  return acq.type === 'given'
}

export function isWon(acq: AcquisitionEvent): acq is WonAcquisition {
  return acq.type === 'won'
}

export function isInherited(acq: AcquisitionEvent): acq is InheritedAcquisition {
  return acq.type === 'inherited'
}

export function getBookDisplayName(book: PhysicalBook): string {
  if (!book.title) {
    return `Book #${book.entity_id}`
  }

  const parts = [book.title]

  if (book.subtitle) {
    parts.push(book.subtitle)
  }

  if (book.author) {
    parts.push(`by ${book.author}`)
  }

  return parts.join(': ')
}
