/**
 * Auto-generated from domains/book-metadata-services.md
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * This file is automatically generated by devtools/watch/tasks/types-from-docs.ts
 * which extracts TypeScript code blocks from the markdown domain documentation.
 *
 * To make changes:
 * 1. Edit the corresponding .md file in /domains
 * 2. The devtools watcher will regenerate automatically
 * 3. Or run manually: bun run devtools/watch/tasks/types-from-docs.ts
 */

export type BookMetadataProvider =
  | "google-books"
  | "open-library"
  | "library-of-congress"
  | "hardcover"
  | "worldcat-classify";

export interface BookMetadata {
  /** The ISBN used for lookup (normalized, hyphens removed) */
  isbn: string;
  /** ISBN-10 identifier if available */
  isbn10?: string;
  /** ISBN-13 identifier if available */
  isbn13?: string;
  /** Library of Congress Control Number */
  lccn?: string;
  /** Book title */
  title: string;
  /** Book subtitle */
  subtitle?: string;
  /** List of author names */
  authors: string[];
  /** Publisher name */
  publisher?: string;
  /** Publication date (ISO format or year string) */
  publishedDate?: string;
  /** Book description/summary */
  description?: string;
  /** Number of pages */
  pageCount?: number;
  /** Language code (e.g., "en", "es") */
  language?: string;
  /** Subject/category tags */
  subjects?: string[];
  /** Thumbnail image URL */
  thumbnailUrl?: string;
  /** Provider that returned this result */
  source: BookMetadataProvider;
}

export interface BookMetadataService {
  /** Look up book metadata by ISBN */
  lookup(isbn: string): Promise<BookMetadata | null>;
  /** The provider name for this service instance */
  readonly provider: BookMetadataProvider;
}

export class BookMetadataServiceError extends Error {
  constructor(
    message: string,
    public readonly provider: BookMetadataProvider | "composite",
    public readonly cause?: Error
  ) {
    super(message);
    this.name = "BookMetadataServiceError";
  }
}

export type CircuitBreakerState = "CLOSED" | "OPEN" | "HALF_OPEN";

export interface CircuitBreakerConfig {
  /** Number of consecutive failures before opening circuit */
  failureThreshold?: number;
  /** Time in milliseconds before trying again after opening */
  recoveryTimeout?: number;
  /** Number of consecutive successes in HALF_OPEN before closing */
  successThreshold?: number;
}

export interface RateLimitConfig {
  /** Maximum number of tokens (burst capacity) */
  maxRequests: number;
  /** Tokens per second */
  perSeconds: number;
}

export interface BaseProviderConfig {
  /** Request timeout in milliseconds (default: 10000) */
  timeout?: number;
  /** Rate limiting configuration (optional) */
  rateLimit?: RateLimitConfig;
  /** Circuit breaker configuration (optional) */
  circuitBreaker?: CircuitBreakerConfig;
}

export interface GoogleBooksConfig extends BaseProviderConfig {
  /** Optional API key for higher rate limits */
  apiKey?: string;
}

export interface HardcoverConfig extends BaseProviderConfig {
  /** API key from hardcover.app/account/api (required) */
  apiKey: string;
}

export type OpenLibraryConfig = BaseProviderConfig;
export type LibraryOfCongressConfig = BaseProviderConfig;
export type WorldCatClassifyConfig = BaseProviderConfig;

export interface CompositeConfig {
  /** Providers to try in order */
  providers: BookMetadataService[];
}
