/**
 * Auto-generated from domains/configuration.md
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * This file is automatically generated by domains/scripts/extract-types.ts
 * which extracts TypeScript code blocks from the markdown domain documentation.
 *
 * To make changes:
 * 1. Edit the corresponding .md file in /domains
 * 2. Run: bun run domains/scripts/extract-types.ts
 * 3. Or commit changes - the pre-commit hook will regenerate automatically
 */

export type Env = {
  // Node environment
  NODE_ENV: 'development' | 'production' | 'test';

  // Server configuration
  PORT: number;
  HOST: string;

  // Database
  DATABASE_URL: string;

  // Authentication
  JWT_SECRET: string;
  JWT_EXPIRES_IN: string;
  JWT_SECRET_OLD?: string;

  // CORS
  CORS_ORIGINS: string;

  // Rate limiting
  RATE_LIMIT_ENABLED: boolean;

  // Logging
  LOG_LEVEL: 'error' | 'warn' | 'info' | 'debug';

  // Book metadata providers (optional)
  GOOGLE_BOOKS_API_KEY?: string;
  OPEN_LIBRARY_API_KEY?: string;

  // Analytics
  ANALYTICS_ENABLED: boolean;
  ANALYTICS_RETENTION_DAYS: number;

  // Observability
  SENTRY_DSN?: string;
  SENTRY_ENABLED: boolean;
  PROMETHEUS_ENABLED: boolean;

  // Security
  PASSWORD_MIN_LENGTH: number;
  PASSWORD_REQUIRE_COMPLEXITY: boolean;
  HTTPS_REDIRECT: boolean;
};

export type EnvironmentCheck = () => boolean;
