/**
 * Auto-generated from domains/configuration.md
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * This file is automatically generated by domains/scripts/extract-types.ts
 * which extracts TypeScript code blocks from the markdown domain documentation.
 *
 * To make changes:
 * 1. Edit the corresponding .md file in /domains
 * 2. Run: bun run domains/scripts/extract-types.ts
 * 3. Or commit changes - the pre-commit hook will regenerate automatically
 */

export type Env = {
  // Node environment
  NODE_ENV: 'development' | 'production' | 'test';

  // Server configuration
  PORT: number;
  HOST: string;

  // Database
  DATABASE_URL: string;

  // Authentication
  JWT_SECRET: string;
  JWT_EXPIRES_IN: string;
  JWT_SECRET_OLD?: string;

  // CORS
  CORS_ORIGINS: string;

  // Rate limiting
  RATE_LIMIT_ENABLED: boolean;

  // Logging
  LOG_LEVEL: 'error' | 'warn' | 'info' | 'debug';

  // Book metadata providers (optional)
  GOOGLE_BOOKS_API_KEY?: string;
  OPEN_LIBRARY_API_KEY?: string;

  // Analytics
  ANALYTICS_ENABLED: boolean;
  ANALYTICS_RETENTION_DAYS: number;

  // Observability
  SENTRY_DSN?: string;
  SENTRY_ENABLED: boolean;
  PROMETHEUS_ENABLED: boolean;

  // Security
  PASSWORD_MIN_LENGTH: number;
  PASSWORD_REQUIRE_COMPLEXITY: boolean;
  HTTPS_REDIRECT: boolean;
};

export type EnvironmentCheck = () => boolean;

import { env, isProduction, isDevelopment, isTest } from '@/domains/types/configuration';

// Type-safe access to configuration
const port = env.PORT; // number
const dbUrl = env.DATABASE_URL; // string

// Readable environment checks
if (isProduction()) {
  // Enable production optimizations
}

if (isDevelopment()) {
  // Enable development tools
}

if (isTest()) {
  // Use test doubles
}

import { env } from '@/server/src/config';

// Start server on configured port
const server = Bun.serve({
  port: env.PORT,
  hostname: env.HOST,
  fetch: handler,
});

console.log(`Server listening on ${env.HOST}:${env.PORT}`);

import { env, isProduction, isDevelopment } from '@/server/src/config';

// Enable features based on environment
const corsOrigins = isProduction()
  ? env.CORS_ORIGINS.split(',')
  : ['*']; // Allow all origins in development

// Conditional logging
if (isDevelopment()) {
  console.log('Database URL:', env.DATABASE_URL);
}

import { env } from '@/server/src/config';

// Conditionally enable analytics
if (env.ANALYTICS_ENABLED) {
  await recordAnalyticsEvent({
    event_type: 'http_request',
    data: { method, path, duration },
  });
}

// Gracefully handle missing API keys
if (env.GOOGLE_BOOKS_API_KEY) {
  const metadata = await googleBooksClient.lookup(isbn);
} else {
  console.warn('Google Books API key not configured, skipping provider');
}

// config.ts validates environment on module load
import { env } from '@/server/src/config';

// If validation fails, the import throws and the app never starts
const server = startServer(env);

// Enable/disable features based on configuration
if (env.RATE_LIMIT_ENABLED) {
  app.use(rateLimitMiddleware);
}

if (env.SENTRY_ENABLED && env.SENTRY_DSN) {
  Sentry.init({ dsn: env.SENTRY_DSN });
}

// Compose metadata services based on available API keys
const providers: BookMetadataProvider[] = [];

if (env.GOOGLE_BOOKS_API_KEY) {
  providers.push(createGoogleBooksProvider(env.GOOGLE_BOOKS_API_KEY));
}

if (env.OPEN_LIBRARY_API_KEY) {
  providers.push(createOpenLibraryProvider(env.OPEN_LIBRARY_API_KEY));
}

const metadataService = createCompositeService(providers);

// Enforce HTTPS in production
if (isProduction() && env.HTTPS_REDIRECT) {
  app.use(httpsRedirectMiddleware);
}

// Strict CORS in production, permissive in development
const corsOrigins = isProduction()
  ? env.CORS_ORIGINS.split(',')
  : ['*'];
