/**
 * Auto-generated from domains/database.md
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * This file is automatically generated by domains/scripts/extract-types.ts
 * which extracts TypeScript code blocks from the markdown domain documentation.
 *
 * To make changes:
 * 1. Edit the corresponding .md file in /domains
 * 2. Run: bun run domains/scripts/extract-types.ts
 * 3. Or commit changes - the pre-commit hook will regenerate automatically
 */

export type Sql = SQL;

export type DbConfig = {
  host: string;           // Database server hostname
  port: number;           // PostgreSQL port (typically 5432)
  database: string;       // Database name
  username: string;       // Database user
  password: string;       // Database password
  ssl: boolean;           // Enable SSL/TLS for connection
  max: number;            // Maximum connections in pool
};

export const getUserBooks: Handler = async (ctx, req) => {
  const { sql } = ctx; // Connection from RequestContext

  const books = await sql`
    SELECT * FROM books
    WHERE user_id = ${ctx.user.id}
    ORDER BY created_at DESC
  `;

  return new Response(JSON.stringify(books), {
    headers: { 'Content-Type': 'application/json' },
  });
};
