/**
 * Auto-generated from domains/database.md
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * This file is automatically generated by domains/scripts/extract-types.ts
 * which extracts TypeScript code blocks from the markdown domain documentation.
 *
 * To make changes:
 * 1. Edit the corresponding .md file in /domains
 * 2. Run: bun run domains/scripts/extract-types.ts
 * 3. Or commit changes - the pre-commit hook will regenerate automatically
 */

export type Sql = SQL;

export type DbConfig = {
  host: string;           // Database server hostname
  port: number;           // PostgreSQL port (typically 5432)
  database: string;       // Database name
  username: string;       // Database user
  password: string;       // Database password
  ssl: boolean;           // Enable SSL/TLS for connection
  max: number;            // Maximum connections in pool
};

import { getConnection } from '@/data/client/src/db/connection';

const sql = getConnection(); // Always returns the same connection
const users = await sql`SELECT * FROM users WHERE email = ${email}`;

import { createConnection } from '@/data/client/src/db/connection';

const sql = createConnection({
  host: 'localhost',
  port: 5432,
  database: 'my_test_db',
  username: 'test_user',
  password: 'test_password',
  ssl: false,
  max: 5,
});

// Use the connection
await sql`SELECT 1`;

// Clean up when done
await sql.close();

import { closeConnection } from '@/data/client/src/db/connection';

// On shutdown signal
process.on('SIGTERM', async () => {
  await closeConnection(); // Closes the default connection pool
  process.exit(0);
});

// Config:
const config = {
  host: 'db.example.com',
  port: 5432,
  database: 'quailcomp',
  username: 'app_user',
  password: 'p@ssw0rd!',
  ssl: true,
  max: 10,
};

// Generated URL:
// postgres://app_user:p%40ssw0rd!@db.example.com:5432/quailcomp?sslmode=require

import { getConnection } from '@/data/client/src/db/connection';

const sql = getConnection();

// Simple query
const result = await sql`SELECT * FROM books WHERE id = ${bookId}`;

// Insert with RETURNING
const [newBook] = await sql`
  INSERT INTO books (title, author, isbn)
  VALUES (${title}, ${author}, ${isbn})
  RETURNING *
`;

// Update
await sql`
  UPDATE books
  SET status = ${newStatus}
  WHERE id = ${bookId}
`;

import { getConnection } from '@/data/client/src/db/connection';

const sql = getConnection();

await sql.begin(async (tx) => {
  // All queries in this block use the same transaction
  const [user] = await tx`
    INSERT INTO users (email, name)
    VALUES (${email}, ${name})
    RETURNING id
  `;

  await tx`
    INSERT INTO user_roles (user_id, role)
    VALUES (${user.id}, ${'reader'})
  `;

  // Transaction commits automatically if no errors
  // Rolls back automatically on error
});

import { createConnection, getTestDbConfig } from '@/data/client/src/db/connection';
import { test, afterAll } from 'bun:test';

const sql = createConnection(getTestDbConfig());

afterAll(async () => {
  await sql.close(); // Clean up connection pool
});

test('user creation', async () => {
  const [user] = await sql`
    INSERT INTO users (email, name)
    VALUES (${'test@example.com'}, ${'Test User'})
    RETURNING *
  `;

  expect(user.email).toBe('test@example.com');
});

import { getConnection } from '@/data/client/src/db/connection';

const sql = getConnection();

// Connection automatically uses environment-specific settings:
// - Development: DB_NAME=quailcomp, DB_HOST=localhost
// - Production: DB_NAME=quailcomp_prod, DB_HOST=prod.db.example.com, DB_SSL=true
// - Test: DB_NAME=quailcomp_test

// Main application entry point
import { getConnection } from '@/data/client/src/db/connection';

// Connection is created lazily on first call
const sql = getConnection();

// Verify database connectivity at startup
try {
  await sql`SELECT 1`;
  console.log('Database connection established');
} catch (error) {
  console.error('Failed to connect to database:', error);
  process.exit(1);
}

// HTTP handler with database access
import type { Handler } from '@/server/src/middleware/types';

export const getUserBooks: Handler = async (ctx, req) => {
  const { sql } = ctx; // Connection from RequestContext

  const books = await sql`
    SELECT * FROM books
    WHERE user_id = ${ctx.user.id}
    ORDER BY created_at DESC
  `;

  return new Response(JSON.stringify(books), {
    headers: { 'Content-Type': 'application/json' },
  });
};

// Database migration script
import { getConnection } from '@/data/client/src/db/connection';

const sql = getConnection();

// Execute migration
await sql`
  CREATE TABLE IF NOT EXISTS books (
    id SERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    author TEXT NOT NULL,
    isbn TEXT UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
  )
`;

console.log('Migration completed');
await sql.close();

// Test file with isolated connection
import { createConnection, getTestDbConfig } from '@/data/client/src/db/connection';

const sql = createConnection({
  ...getTestDbConfig(),
  database: `quailcomp_test_${Date.now()}`, // Unique DB per test file
});

test('parallel test 1', async () => {
  // Each test file has its own connection pool
  await sql`INSERT INTO books (title) VALUES (${'Book 1'})`;
});

afterAll(async () => {
  await sql.close();
});
