/**
 * Auto-generated from domains/devtools.md
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * This file is automatically generated by devtools/watch/tasks/types-from-docs.ts
 * which extracts TypeScript code blocks from the markdown domain documentation.
 *
 * To make changes:
 * 1. Edit the corresponding .md file in /domains
 * 2. The devtools watcher will regenerate automatically
 * 3. Or run manually: bun run devtools/watch/tasks/types-from-docs.ts
 */

export interface WatchRule {
  name: string; // "type-generation"
  description: string; // "Extract types from domain docs"
  watch: string[]; // ["domains/**/*.md"]
  run: WatchTask; // Function or command string
  debounce?: number; // ms (default: 300)
  runOnStart?: boolean; // Run immediately (default: false)
}

export type WatchTask =
  | string // Shell command
  | ((changed: string[]) => Promise<TaskResult>); // Function

export interface TaskResult {
  success: boolean;
  stdout: string;
  stderr: string;
  duration: number; // ms
  error?: Error;
}

export interface TaskExecution {
  ruleName: string;
  timestamp: number;
  duration: number;
  status: 'success' | 'error' | 'warning';
  stdout: string;
  stderr: string;
  changedFiles: string[];
}

export type TaskExecutor = {
  execute: (rule: WatchRule, changedFiles: string[]) => Promise<void>;
  getHistory: () => TaskExecution[];
  clearHistory: () => void;
};

export interface TaskExecutorCallbacks {
  onExecutionStart: (ruleName: string) => void;
  onExecutionEnd: (execution: TaskExecution) => void;
}

export interface WatcherState {
  rules: WatchRule[]; // All registered watch rules
  executions: TaskExecution[]; // Last 100 executions (circular buffer)
  currentlyRunning: Set<string>; // Rule names currently executing
}

export const MAX_EXECUTIONS = 100;
