/**
 * Auto-generated from domains/entities.md
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * This file is automatically generated by domains/scripts/extract-types.ts
 * which extracts TypeScript code blocks from the markdown domain documentation.
 *
 * To make changes:
 * 1. Edit the corresponding .md file in /domains
 * 2. Run: bun run domains/scripts/extract-types.ts
 * 3. Or commit changes - the pre-commit hook will regenerate automatically
 */

export type Entry<T = unknown> = {
  entryId: number;        // Unique ID for this entry (auto-generated)
  enteredAt: Date;        // When this entry was created
  type: string;           // Entity type (e.g., 'user', 'book', 'series')
  data: T;                // Entity data (JSONB, type-safe)
  entityId: number;       // Entity ID (multiple entries share this)
  deletedAt: Date | null; // Soft delete timestamp (null if not deleted)
};

export type CreateEntityInput<T = unknown> = {
  type: string;  // Entity type
  data: T;       // Initial entity data
};

export type UpdateEntityInput<T = unknown> = {
  entityId: number; // Which entity to update
  type: string;     // Entity type (must match existing)
  data: T;          // New entity data
};

export type DeleteEntityInput<T = unknown> = {
  entityId: number; // Which entity to delete
  type: string;     // Entity type (must match existing)
  data: T;          // Final entity data (preserved for audit)
};

export type QueryOptions = {
  /** Include soft-deleted entities (default: false) */
  includeDeleted?: boolean;
  /** Limit number of results */
  limit?: number;
  /** Offset for pagination */
  offset?: number;
};

const client = createEntitiesClient(sql);

const entry = await client.create({
  type: 'user',
  data: { email: 'alice@example.com', name: 'Alice' },
});

// entry.entityId is auto-generated
// entry.entryId is unique for this version

const entries = await client.createMany([
  { type: 'book', data: { title: 'Book 1', author: 'Author 1' } },
  { type: 'book', data: { title: 'Book 2', author: 'Author 2' } },
]);

// All succeed or all fail (wrapped in transaction)

const updatedEntry = await client.update({
  entityId: 123,
  type: 'user',
  data: { email: 'alice@example.com', name: 'Alice Smith' },
});

// Creates new entry with same entityId, new enteredAt
// Previous entry remains in database

const deletedEntry = await client.delete({
  entityId: 123,
  type: 'user',
  data: { email: 'alice@example.com', name: 'Alice Smith' },
});

// Creates new entry with deletedAt set
// Entity no longer returned by default queries

const restoredEntry = await client.restore({
  entityId: 123,
  type: 'user',
  data: { email: 'alice@example.com', name: 'Alice Smith' },
});

// Creates new entry with deletedAt = null
// Entity is active again

const user = await client.getById<UserData>(123);

if (!user) {
  // Entity doesn't exist or is soft-deleted
}

// Include deleted entities
const deletedUser = await client.getById<UserData>(123, { includeDeleted: true });

const history = await client.getHistory<UserData>(123);

// Returns all entries for entity 123, ordered oldest to newest
// Shows how entity evolved over time
history.forEach((entry) => {
  console.log(`Version at ${entry.enteredAt}:`, entry.data);
});

const users = await client.getByType<UserData>('user');

// Returns latest entry for each user entity
// Excludes soft-deleted by default

const allUsers = await client.getByType<UserData>('user', { includeDeleted: true });

const activeCount = await client.countByType('user');
const totalCount = await client.countByType('user', { includeDeleted: true });

const exists = await client.exists(123);

// Returns true if entity exists and is not soft-deleted

// Find users where data contains { status: 'active' }
const activeUsers = await client.findByData<UserData>(
  'user',
  { status: 'active' },
);

// Find books by author
const booksByAuthor = await client.findByData<BookData>(
  'book',
  { author: 'J.K. Rowling' },
  { limit: 10 },
);

import { createEntitiesClient } from '@quailcomp/data';
import { getConnection } from '@quailcomp/data';

const sql = getConnection();
const client = createEntitiesClient(sql);

// 1. Create entity
const created = await client.create({
  type: 'book',
  data: { title: 'The Hobbit', author: 'J.R.R. Tolkien', year: 1937 },
});

console.log('Created:', created.entityId);

// 2. Update entity
const updated = await client.update({
  entityId: created.entityId,
  type: 'book',
  data: { title: 'The Hobbit', author: 'J.R.R. Tolkien', year: 1937, pages: 310 },
});

// 3. Get current state
const current = await client.getById(created.entityId);
console.log('Current:', current?.data);

// 4. View history
const history = await client.getHistory(created.entityId);
console.log('History:', history.length, 'versions');

// 5. Soft delete
await client.delete({
  entityId: created.entityId,
  type: 'book',
  data: current!.data,
});

// 6. Verify deleted
const deleted = await client.getById(created.entityId);
console.log('Deleted:', deleted === null); // true

// Define entity data types
type UserData = {
  email: string;
  name: string;
  status: 'active' | 'suspended';
};

type BookData = {
  title: string;
  author: string;
  isbn?: string;
};

// Type-safe operations
const user = await client.create<UserData>({
  type: 'user',
  data: {
    email: 'alice@example.com',
    name: 'Alice',
    status: 'active',
  },
});

// TypeScript knows user.data is UserData
console.log(user.data.email); // OK
console.log(user.data.title); // Error: Property 'title' does not exist

// Get first page of users
const page1 = await client.getByType<UserData>('user', {
  limit: 10,
  offset: 0,
});

// Get second page
const page2 = await client.getByType<UserData>('user', {
  limit: 10,
  offset: 10,
});

// Get total count
const total = await client.countByType('user');
const pages = Math.ceil(total / 10);

// Find users by nested fields
const users = await client.findByData<UserData>(
  'user',
  { preferences: { theme: 'dark' } },
);

// Find books by partial match
const sciFiBooks = await client.findByData<BookData>(
  'book',
  { genres: ['science-fiction'] }, // Matches if array contains 'science-fiction'
);

// Update multiple related entities atomically
await sql.begin(async (tx) => {
  const txClient = createEntitiesClient(tx);

  // Create user
  const user = await txClient.create({
    type: 'user',
    data: { email: 'bob@example.com', name: 'Bob' },
  });

  // Create associated profile
  await txClient.create({
    type: 'profile',
    data: { userId: user.entityId, bio: 'Software engineer' },
  });

  // If either fails, both roll back
});

// Create user
const user = await client.create<UserData>({
  type: 'user',
  data: { email: 'alice@example.com', name: 'Alice', status: 'active' },
});

// Update user profile
await client.update<UserData>({
  entityId: user.entityId,
  type: 'user',
  data: { ...user.data, name: 'Alice Smith' },
});

// Suspend user
await client.update<UserData>({
  entityId: user.entityId,
  type: 'user',
  data: { ...user.data, status: 'suspended' },
});

// View audit trail
const history = await client.getHistory<UserData>(user.entityId);

// Add book to library
const book = await client.create<BookData>({
  type: 'book',
  data: { title: 'The Hobbit', author: 'J.R.R. Tolkien' },
});

// Update book metadata
await client.update<BookData>({
  entityId: book.entityId,
  type: 'book',
  data: { ...book.data, isbn: '978-0547928227', year: 1937 },
});

// Remove book from library (soft delete)
await client.delete<BookData>({
  entityId: book.entityId,
  type: 'book',
  data: book.data,
});

// Restore book
await client.restore<BookData>({
  entityId: book.entityId,
  type: 'book',
  data: book.data,
});

// Find active users
const activeUsers = await client.findByData<UserData>(
  'user',
  { status: 'active' },
);

// Find books by author
const tolkienBooks = await client.findByData<BookData>(
  'book',
  { author: 'J.R.R. Tolkien' },
);

// List all users (paginated)
const users = await client.getByType<UserData>('user', {
  limit: 20,
  offset: 0,
});

// View entity evolution
const history = await client.getHistory<UserData>(userId);

history.forEach((entry, index) => {
  console.log(`Version ${index + 1} at ${entry.enteredAt}:`);
  console.log('Data:', entry.data);
  console.log('Deleted:', entry.deletedAt !== null);
});

// Find when entity was deleted
const deletedEntry = history.find((e) => e.deletedAt !== null);
if (deletedEntry) {
  console.log('Deleted at:', deletedEntry.deletedAt);
}

// Create multiple entities efficiently
const books = await client.createMany<BookData>([
  { type: 'book', data: { title: 'Book 1', author: 'Author 1' } },
  { type: 'book', data: { title: 'Book 2', author: 'Author 2' } },
  { type: 'book', data: { title: 'Book 3', author: 'Author 3' } },
]);

console.log(`Created ${books.length} books`);
