/**
 * Auto-generated from domains/entities.md
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * This file is automatically generated by domains/scripts/extract-types.ts
 * which extracts TypeScript code blocks from the markdown domain documentation.
 *
 * To make changes:
 * 1. Edit the corresponding .md file in /domains
 * 2. Run: bun run domains/scripts/extract-types.ts
 * 3. Or commit changes - the pre-commit hook will regenerate automatically
 */

export type Entry<T = unknown> = {
  entryId: number;        // Unique ID for this entry (auto-generated)
  enteredAt: Date;        // When this entry was created
  type: string;           // Entity type (e.g., 'user', 'book', 'series')
  data: T;                // Entity data (JSONB, type-safe)
  entityId: number;       // Entity ID (multiple entries share this)
  deletedAt: Date | null; // Soft delete timestamp (null if not deleted)
};

export type CreateEntityInput<T = unknown> = {
  type: string;  // Entity type
  data: T;       // Initial entity data
};
export type UpdateEntityInput<T = unknown> = {
  entityId: number; // Which entity to update
  type: string;     // Entity type (must match existing)
  data: T;          // New entity data
};
export type DeleteEntityInput<T = unknown> = {
  entityId: number; // Which entity to delete
  type: string;     // Entity type (must match existing)
  data: T;          // Final entity data (preserved for audit)
};

export type QueryOptions = {
  /** Include soft-deleted entities (default: false) */
  includeDeleted?: boolean;
  /** Limit number of results */
  limit?: number;
  /** Offset for pagination */
  offset?: number;
};
