/**
 * Auto-generated from domains/errors.md
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * This file is automatically generated by devtools/watch/tasks/types-from-docs.ts
 * which extracts TypeScript code blocks from the markdown domain documentation.
 *
 * To make changes:
 * 1. Edit the corresponding .md file in /domains
 * 2. The devtools watcher will regenerate automatically
 * 3. Or run manually: bun run devtools/watch/tasks/types-from-docs.ts
 */

export type ErrorResponse = {
  /** Human-readable error message */
  error: string;

  /** Machine-readable error code (UPPER_SNAKE_CASE) */
  code: string;

  /** Optional additional details (validation errors, context, etc.) */
  details?: Record<string, unknown>;

  /** The request path where the error occurred */
  path?: string;

  /** Request ID for tracking */
  requestId?: string;
};

export type ValidationErrorDetail = {
  field: string; // Field path (e.g., 'email', 'book.title')
  message: string; // Human-readable validation error
  value?: unknown; // The invalid value (if safe to include)
};

export type ValidationErrorResponse = ErrorResponse & {
  code: "VALIDATION_ERROR";
  details: {
    fields: ValidationErrorDetail[];
  };
};

export type DatabaseErrorCode =
  | "UNIQUE_VIOLATION" // Duplicate key (e.g., email already exists)
  | "FOREIGN_KEY_VIOLATION" // Referenced entity doesn't exist
  | "NOT_NULL_VIOLATION" // Required field is null
  | "CHECK_VIOLATION" // Check constraint failed
  | "CONNECTION_ERROR" // Cannot connect to database
  | "QUERY_ERROR" // Invalid SQL or query execution failed
  | "NOT_FOUND" // Entity or event not found
  | "UNKNOWN_ERROR"; // Unclassified error

export type DatabaseErrorParser = (error: unknown, operation: string) => DatabaseError;

import type { ErrorResponse } from '@/domains/types/errors';
import type { RequestContext } from '@/server/src/context';

// Return error response from handler
async function handleGetUser(ctx: RequestContext): Promise<Response> {
  const userId = parseInt(ctx.params.id);

  try {
    const user = await getUserById(ctx.sql, userId);
    return new Response(JSON.stringify(user));
  } catch (error) {
    const errorResponse: ErrorResponse = {
      error: 'User not found',
      code: 'NOT_FOUND',
      path: ctx.request.url,
      requestId: ctx.request_id,
    };

    return new Response(JSON.stringify(errorResponse), {
      status: 404,
      headers: { 'Content-Type': 'application/json' },
    });
  }
}

import type { ValidationErrorResponse, ValidationErrorDetail } from '@/domains/types/errors';

async function handleCreateBook(ctx: RequestContext): Promise<Response> {
  const body = await ctx.request.json();

  const errors: ValidationErrorDetail[] = [];

  if (!body.title) {
    errors.push({ field: 'title', message: 'Title is required' });
  }

  if (!body.isbn) {
    errors.push({ field: 'isbn', message: 'ISBN is required' });
  } else if (!/^\d{13}$/.test(body.isbn)) {
    errors.push({ field: 'isbn', message: 'ISBN must be 13 digits', value: body.isbn });
  }

  if (errors.length > 0) {
    const errorResponse: ValidationErrorResponse = {
      error: 'Validation failed',
      code: 'VALIDATION_ERROR',
      details: { fields: errors },
      path: ctx.request.url,
      requestId: ctx.request_id,
    };

    return new Response(JSON.stringify(errorResponse), {
      status: 400,
      headers: { 'Content-Type': 'application/json' },
    });
  }

  // Proceed with valid data
  const book = await createBook(ctx.sql, body);
  return new Response(JSON.stringify(book), { status: 201 });
}

import { parseDatabaseError, EntityNotFoundError, UniqueViolationError } from '@/data/client/src/errors';
import type { Sql } from '@/domains/types/database';

async function createUser(sql: Sql, email: string, username: string) {
  try {
    const result = await sql`
      INSERT INTO users (email, username)
      VALUES (${email}, ${username})
      RETURNING *
    `;
    return result[0];
  } catch (error) {
    const dbError = parseDatabaseError(error, 'createUser');

    if (dbError instanceof UniqueViolationError) {
      if (dbError.constraint.includes('email')) {
        throw new Error('Email already in use');
      }
      if (dbError.constraint.includes('username')) {
        throw new Error('Username already taken');
      }
    }

    throw dbError;
  }
}

import { EntityNotFoundError } from '@/data/client/src/errors';

async function getBookOrNull(sql: Sql, bookId: number): Promise<Book | null> {
  try {
    return await getBookById(sql, bookId);
  } catch (error) {
    if (error instanceof EntityNotFoundError) {
      return null; // Graceful fallback
    }
    throw error; // Re-throw unexpected errors
  }
}

import { parseDatabaseError } from '@/data/client/src/errors';
import type { Logger } from '@/domains/types/logging';

async function updateBook(sql: Sql, logger: Logger, bookId: number, updates: Partial<Book>) {
  try {
    const result = await sql`
      UPDATE books
      SET ${sql(updates)}
      WHERE book_id = ${bookId}
      RETURNING *
    `;

    if (result.length === 0) {
      throw new EntityNotFoundError(bookId, 'book');
    }

    return result[0];
  } catch (error) {
    const dbError = parseDatabaseError(error, 'updateBook');

    logger.error('Failed to update book', {
      book_id: bookId,
      error_code: dbError.code,
      error_message: dbError.message,
      operation: dbError.operation,
      details: dbError.details,
    });

    throw dbError;
  }
}

// Client code parsing error responses
async function fetchBooks() {
  const response = await fetch('/api/books');

  if (!response.ok) {
    const error: ErrorResponse = await response.json();

    switch (error.code) {
      case 'VALIDATION_ERROR':
        // Show field-level validation errors
        const validationError = error as ValidationErrorResponse;
        displayFieldErrors(validationError.details.fields);
        break;

      case 'NOT_FOUND':
        // Show not found message
        showError('Books not found');
        break;

      case 'UNAUTHORIZED':
        // Redirect to login
        redirectToLogin();
        break;

      default:
        // Generic error handling
        showError(error.error);
    }
  }

  return response.json();
}

import { parseDatabaseError } from '@/data/client/src/errors';

async function queryWithRetry<T>(sql: Sql, query: string, maxRetries = 3): Promise<T[]> {
  for (let attempt = 0; attempt < maxRetries; attempt++) {
    try {
      return await sql.query<T>(query);
    } catch (error) {
      const dbError = parseDatabaseError(error, 'query');

      // Retry on connection errors
      if (dbError.code === 'CONNECTION_ERROR' && attempt < maxRetries - 1) {
        await sleep(1000 * Math.pow(2, attempt)); // Exponential backoff
        continue;
      }

      throw dbError;
    }
  }

  throw new Error('Max retries exceeded');
}

import { metrics } from '@/server/src/metrics/collector';
import { parseDatabaseError } from '@/data/client/src/errors';

async function executeQuery(sql: Sql, query: string) {
  try {
    return await sql.query(query);
  } catch (error) {
    const dbError = parseDatabaseError(error, 'query');

    // Track error metrics by type
    metrics.inc('database_errors_total', {
      error_code: dbError.code,
      operation: dbError.operation,
    });

    throw dbError;
  }
}
