/**
 * Auto-generated from domains/errors.md
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * This file is automatically generated by domains/scripts/extract-types.ts
 * which extracts TypeScript code blocks from the markdown domain documentation.
 *
 * To make changes:
 * 1. Edit the corresponding .md file in /domains
 * 2. Run: bun run domains/scripts/extract-types.ts
 * 3. Or commit changes - the pre-commit hook will regenerate automatically
 */

export type ErrorResponse = {
  /** Human-readable error message */
  error: string;

  /** Machine-readable error code (UPPER_SNAKE_CASE) */
  code: string;

  /** Optional additional details (validation errors, context, etc.) */
  details?: Record<string, unknown>;

  /** The request path where the error occurred */
  path?: string;

  /** Request ID for tracking */
  requestId?: string;
};

export type ValidationErrorDetail = {
  field: string; // Field path (e.g., 'email', 'book.title')
  message: string; // Human-readable validation error
  value?: unknown; // The invalid value (if safe to include)
};
export type ValidationErrorResponse = ErrorResponse & {
  code: "VALIDATION_ERROR";
  details: {
    fields: ValidationErrorDetail[];
  };
};

export type DatabaseErrorCode =
  | "UNIQUE_VIOLATION" // Duplicate key (e.g., email already exists)
  | "FOREIGN_KEY_VIOLATION" // Referenced entity doesn't exist
  | "NOT_NULL_VIOLATION" // Required field is null
  | "CHECK_VIOLATION" // Check constraint failed
  | "CONNECTION_ERROR" // Cannot connect to database
  | "QUERY_ERROR" // Invalid SQL or query execution failed
  | "NOT_FOUND" // Entity or event not found
  | "UNKNOWN_ERROR"; // Unclassified error

export type DatabaseErrorParser = (error: unknown, operation: string) => DatabaseError;
