/**
 * Auto-generated from domains/events.md
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * This file is automatically generated by devtools/watch/tasks/types-from-docs.ts
 * which extracts TypeScript code blocks from the markdown domain documentation.
 *
 * To make changes:
 * 1. Edit the corresponding .md file in /domains
 * 2. The devtools watcher will regenerate automatically
 * 3. Or run manually: bun run devtools/watch/tasks/types-from-docs.ts
 */

export type EventEntry<T = unknown> = {
  entryId: number;         // Unique ID for this entry (auto-generated)
  enteredAt: Date;         // When this entry was created
  eventType: string;       // Event type (e.g., 'user_logged_in', 'book_acquired')
  occurredAt: Date;        // When the event actually occurred
  data: T;                 // Event data (JSONB, type-safe)
  eventId: number;         // Event ID (multiple entries share this for enrichment)
  voidedAt: Date | null;   // Void timestamp (null if not voided)
};

export type RecordEventInput<T = unknown> = {
  eventType: string;   // Event type
  occurredAt: Date;    // When event occurred
  data: T;             // Event data
};

export type EnrichEventInput<T = unknown> = {
  eventId: number;     // Which event to enrich
  eventType: string;   // Event type (must match existing)
  occurredAt: Date;    // When event occurred (must match existing)
  data: T;             // Enriched event data
};

export type VoidEventInput<T = unknown> = {
  eventId: number;     // Which event to void
  eventType: string;   // Event type (must match existing)
  occurredAt: Date;    // When event occurred (must match existing)
  data: T;             // Final event data (preserved for audit)
};

export type EventQueryOptions = {
  /** Include voided events (default: false) */
  includeVoided?: boolean;
  /** Limit number of results */
  limit?: number;
  /** Offset for pagination */
  offset?: number;
};

const client = createEventsClient(sql);

const event = await client.record({
  eventType: 'user_logged_in',
  occurredAt: new Date(),
  data: { userId: 123, ipAddress: '192.168.1.1' },
});

// event.eventId is auto-generated
// event.entryId is unique for this entry

const events = await client.recordMany([
  {
    eventType: 'book_added',
    occurredAt: new Date(),
    data: { bookId: 1, userId: 123 },
  },
  {
    eventType: 'book_added',
    occurredAt: new Date(),
    data: { bookId: 2, userId: 123 },
  },
]);

// All succeed or all fail (wrapped in transaction)

// Original event
const event = await client.record({
  eventType: 'book_searched',
  occurredAt: new Date(),
  data: { query: 'tolkien', userId: 123 },
});

// Later: enrich with search results
const enriched = await client.enrich({
  eventId: event.eventId,
  eventType: event.eventType,
  occurredAt: event.occurredAt, // Must match original
  data: {
    query: 'tolkien',
    userId: 123,
    resultCount: 42,
    executionTimeMs: 15,
  },
});

// Creates new entry with same eventId, enriched data
// Previous entry remains in database

const voided = await client.void({
  eventId: 123,
  eventType: 'user_logged_in',
  occurredAt: event.occurredAt,
  data: event.data,
});

// Creates new entry with voidedAt set
// Event no longer returned by default queries

const restored = await client.restore({
  eventId: 123,
  eventType: 'user_logged_in',
  occurredAt: event.occurredAt,
  data: event.data,
});

// Creates new entry with voidedAt = null
// Event is active again

const event = await client.getById<LoginEventData>(123);

if (!event) {
  // Event doesn't exist or is voided
}

// Include voided events
const voidedEvent = await client.getById<LoginEventData>(123, { includeVoided: true });

const history = await client.getHistory<SearchEventData>(123);

// Returns all entries for event 123, ordered oldest to newest
// Shows how event was enriched over time
history.forEach((entry) => {
  console.log(`Version at ${entry.enteredAt}:`, entry.data);
});

const logins = await client.getByType<LoginEventData>('user_logged_in');

// Returns latest entry for each login event
// Excludes voided by default

const allLogins = await client.getByType<LoginEventData>('user_logged_in', {
  includeVoided: true,
});

const startDate = new Date('2024-01-01');
const endDate = new Date('2024-01-31');

const events = await client.getByTimeRange<ActivityEventData>(
  startDate,
  endDate,
  { limit: 100 },
);

// Returns events that occurred in January 2024
// Sorted by occurredAt descending (most recent first)

const activeCount = await client.countByType('user_logged_in');
const totalCount = await client.countByType('user_logged_in', { includeVoided: true });

const exists = await client.exists(123);

// Returns true if event exists and is not voided

// Find login events from specific user
const userLogins = await client.findByData<LoginEventData>(
  'user_logged_in',
  { userId: 123 },
);

// Find search events with specific query
const searches = await client.findByData<SearchEventData>(
  'book_searched',
  { query: 'tolkien' },
  { limit: 10 },
);

// Find all events related to book 123
const bookEvents = await client.findForEntity(
  'bookId',
  123,
);

// Returns events where data.bookId = 123
// Across all event types

import { createEventsClient } from '@quailcomp/data';
import { getConnection } from '@quailcomp/data';

const sql = getConnection();
const client = createEventsClient(sql);

// 1. Record event
const event = await client.record({
  eventType: 'user_logged_in',
  occurredAt: new Date(),
  data: { userId: 123, ipAddress: '192.168.1.1' },
});

console.log('Recorded:', event.eventId);

// 2. Enrich with additional data
const enriched = await client.enrich({
  eventId: event.eventId,
  eventType: event.eventType,
  occurredAt: event.occurredAt,
  data: {
    userId: 123,
    ipAddress: '192.168.1.1',
    userAgent: 'Mozilla/5.0...',
    sessionId: 'abc123',
  },
});

// 3. View history
const history = await client.getHistory(event.eventId);
console.log('History:', history.length, 'versions');

// 4. Void event (e.g., detected as fraudulent)
await client.void({
  eventId: event.eventId,
  eventType: event.eventType,
  occurredAt: event.occurredAt,
  data: enriched.data,
});

// 5. Verify voided
const voided = await client.getById(event.eventId);
console.log('Voided:', voided === null); // true

// Define event data types
type LoginEventData = {
  userId: number;
  ipAddress: string;
  userAgent?: string;
  sessionId?: string;
};

type SearchEventData = {
  userId: number;
  query: string;
  resultCount?: number;
  executionTimeMs?: number;
};

// Type-safe operations
const login = await client.record<LoginEventData>({
  eventType: 'user_logged_in',
  occurredAt: new Date(),
  data: {
    userId: 123,
    ipAddress: '192.168.1.1',
  },
});

// TypeScript knows login.data is LoginEventData
console.log(login.data.userId); // OK
console.log(login.data.query); // Error: Property 'query' does not exist

// Get login events for the last 30 days
const thirtyDaysAgo = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000);
const now = new Date();

const logins = await client.getByTimeRange<LoginEventData>(
  thirtyDaysAgo,
  now,
);

// Count unique users
const uniqueUsers = new Set(logins.map((e) => e.data.userId));
console.log('Unique users logged in:', uniqueUsers.size);

// Group by day
const loginsByDay = logins.reduce((acc, event) => {
  const day = event.occurredAt.toISOString().split('T')[0];
  acc[day] = (acc[day] || 0) + 1;
  return acc;
}, {} as Record<string, number>);

console.log('Logins by day:', loginsByDay);

// Record important actions
await client.record({
  eventType: 'user_deleted',
  occurredAt: new Date(),
  data: {
    userId: 123,
    deletedBy: 456, // Admin user ID
    reason: 'Requested account deletion',
  },
});

await client.record({
  eventType: 'data_exported',
  occurredAt: new Date(),
  data: {
    userId: 123,
    exportedBy: 456,
    exportType: 'full_account_data',
    recordCount: 1247,
  },
});

// Later: audit trail query
const auditEvents = await client.findForEntity('userId', 123);
console.log('Audit trail:', auditEvents);

// Initial event (minimal data)
const search = await client.record({
  eventType: 'book_searched',
  occurredAt: new Date(),
  data: { query: 'tolkien', userId: 123 },
});

// Execute search (async)
const results = await performSearch('tolkien');

// Enrich with results
await client.enrich({
  eventId: search.eventId,
  eventType: search.eventType,
  occurredAt: search.occurredAt,
  data: {
    query: 'tolkien',
    userId: 123,
    resultCount: results.length,
    executionTimeMs: results.duration,
    topResults: results.slice(0, 5).map((r) => r.id),
  },
});

// Get first page of events
const page1 = await client.getByType<ActivityEventData>('user_activity', {
  limit: 20,
  offset: 0,
});

// Get second page
const page2 = await client.getByType<ActivityEventData>('user_activity', {
  limit: 20,
  offset: 20,
});

// Get total count
const total = await client.countByType('user_activity');
const pages = Math.ceil(total / 20);

// Track login
await client.record({
  eventType: 'user_logged_in',
  occurredAt: new Date(),
  data: { userId: 123, ipAddress: '192.168.1.1' },
});

// Track logout
await client.record({
  eventType: 'user_logged_out',
  occurredAt: new Date(),
  data: { userId: 123, sessionDuration: 3600 },
});

// Query activity
const activity = await client.findForEntity('userId', 123);

// Book acquired
await client.record({
  eventType: 'book_acquired',
  occurredAt: new Date(),
  data: { bookId: 1, userId: 123, source: 'purchase' },
});

// Book read
await client.record({
  eventType: 'book_read',
  occurredAt: new Date(),
  data: { bookId: 1, userId: 123, pagesRead: 310, completionPercentage: 100 },
});

// Analytics: most read books
const readEvents = await client.getByType('book_read');
const bookCounts = readEvents.reduce((acc, e) => {
  const bookId = e.data.bookId;
  acc[bookId] = (acc[bookId] || 0) + 1;
  return acc;
}, {});

// Record search
const search = await client.record({
  eventType: 'search_performed',
  occurredAt: new Date(),
  data: { query: 'tolkien', userId: 123 },
});

// Enrich with results
await client.enrich({
  eventId: search.eventId,
  eventType: search.eventType,
  occurredAt: search.occurredAt,
  data: {
    query: 'tolkien',
    userId: 123,
    resultCount: 42,
    clickedResult: 5,
  },
});

// Analytics: top searches
const searches = await client.getByType('search_performed', { limit: 100 });
const queryFrequency = searches.reduce((acc, e) => {
  const query = e.data.query;
  acc[query] = (acc[query] || 0) + 1;
  return acc;
}, {});

// Record data access
await client.record({
  eventType: 'data_accessed',
  occurredAt: new Date(),
  data: {
    userId: 123,
    accessedBy: 456, // Admin ID
    dataType: 'personal_information',
    reason: 'Support ticket #789',
  },
});

// Record data modification
await client.record({
  eventType: 'data_modified',
  occurredAt: new Date(),
  data: {
    userId: 123,
    modifiedBy: 456,
    field: 'email',
    oldValue: 'old@example.com',
    newValue: 'new@example.com',
  },
});

// Audit query: who accessed user 123's data?
const accessEvents = await client.findByData('data_accessed', { userId: 123 });
