/**
 * Auto-generated from domains/events.md
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * This file is automatically generated by devtools/watch/tasks/types-from-docs.ts
 * which extracts TypeScript code blocks from the markdown domain documentation.
 *
 * To make changes:
 * 1. Edit the corresponding .md file in /domains
 * 2. The devtools watcher will regenerate automatically
 * 3. Or run manually: bun run devtools/watch/tasks/types-from-docs.ts
 */

export type EventEntry<T = unknown> = {
  entryId: number;         // Unique ID for this entry (auto-generated)
  enteredAt: Date;         // When this entry was created
  eventType: string;       // Event type (e.g., 'user_logged_in', 'book_acquired')
  occurredAt: Date;        // When the event actually occurred
  data: T;                 // Event data (JSONB, type-safe)
  eventId: number;         // Event ID (multiple entries share this for enrichment)
  voidedAt: Date | null;   // Void timestamp (null if not voided)
};

export type RecordEventInput<T = unknown> = {
  eventType: string;   // Event type
  occurredAt: Date;    // When event occurred
  data: T;             // Event data
};
export type EnrichEventInput<T = unknown> = {
  eventId: number;     // Which event to enrich
  eventType: string;   // Event type (must match existing)
  occurredAt: Date;    // When event occurred (must match existing)
  data: T;             // Enriched event data
};
export type VoidEventInput<T = unknown> = {
  eventId: number;     // Which event to void
  eventType: string;   // Event type (must match existing)
  occurredAt: Date;    // When event occurred (must match existing)
  data: T;             // Final event data (preserved for audit)
};

export type EventQueryOptions = {
  /** Include voided events (default: false) */
  includeVoided?: boolean;
  /** Limit number of results */
  limit?: number;
  /** Offset for pagination */
  offset?: number;
};
