/**
 * Auto-generated from domains/http.md
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * This file is automatically generated by devtools/watch/tasks/types-from-docs.ts
 * which extracts TypeScript code blocks from the markdown domain documentation.
 *
 * To make changes:
 * 1. Edit the corresponding .md file in /domains
 * 2. The devtools watcher will regenerate automatically
 * 3. Or run manually: bun run devtools/watch/tasks/types-from-docs.ts
 */

import type { Sql } from "./database";
import type { Logger } from "./logging";
export type RequestContext = {
  /** Unique identifier for this request (for tracing) */
  requestId: string;

  /** Request start time in milliseconds */
  startTime: number;

  /** Authenticated user (null if unauthenticated) */
  user: AuthenticatedUser | null;

  /** Database connection */
  sql: Sql;

  /** Logger scoped to this request */
  log: Logger;

  /** URL path parameters extracted by router */
  params: Record<string, string>;
};

export type Handler = (
  ctx: RequestContext,
  req: Request
) => Promise<Response> | Response;

export type Middleware = (next: Handler) => Handler;

export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'OPTIONS';
export type Route = {
  method: HttpMethod;
  path: string;
  handler: Handler;
  middleware?: Middleware[];
};
export type RouteMatch = {
  route: Route;
  params: Record<string, string>;
};

export type AuthenticatedUser = {
  userId: number;         // Primary key from users table
  email: string;          // User's email address
  username: string | null; // Username (may be null)
  credentialId: number;   // Which credential was used (for multi-credential users)
  authMethod: string;     // How they authenticated (e.g., 'password', 'google')
};
