/**
 * Auto-generated from domains/http.md
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * This file is automatically generated by devtools/watch/tasks/types-from-docs.ts
 * which extracts TypeScript code blocks from the markdown domain documentation.
 *
 * To make changes:
 * 1. Edit the corresponding .md file in /domains
 * 2. The devtools watcher will regenerate automatically
 * 3. Or run manually: bun run devtools/watch/tasks/types-from-docs.ts
 */

export type RequestContext = {
  /** Unique identifier for this request (for tracing) */
  requestId: string;

  /** Request start time in milliseconds */
  startTime: number;

  /** Authenticated user (null if unauthenticated) */
  user: AuthenticatedUser | null;

  /** Database connection */
  sql: Sql;

  /** Logger scoped to this request */
  log: Logger;

  /** URL path parameters extracted by router */
  params: Record<string, string>;
};

export type Handler = (
  ctx: RequestContext,
  req: Request
) => Promise<Response> | Response;

import type { Handler } from '@/domains/types/http';

export const getUser: Handler = async (ctx, req) => {
  // Access authenticated user
  if (!ctx.user) {
    return new Response('Unauthorized', { status: 401 });
  }

  // Use database connection from context
  const [user] = await ctx.sql`
    SELECT id, email, username, created_at
    FROM users
    WHERE id = ${ctx.user.userId}
  `;

  // Log with request-scoped logger
  ctx.log.info('User fetched', { userId: user.id });

  return new Response(JSON.stringify(user), {
    headers: { 'Content-Type': 'application/json' },
  });
};

export type Middleware = (next: Handler) => Handler;

import type { Middleware } from '@/domains/types/http';

// Authentication middleware: populate ctx.user from JWT
export const requireAuth: Middleware = (next) => {
  return async (ctx, req) => {
    const token = req.headers.get('Authorization')?.replace('Bearer ', '');

    if (!token) {
      return new Response('Missing token', { status: 401 });
    }

    try {
      const user = await verifyJWT(token);
      ctx.user = user; // Augment context
      return next(ctx, req); // Continue to handler
    } catch (error) {
      return new Response('Invalid token', { status: 401 });
    }
  };
};

// Logging middleware: log request/response
export const requestLogger: Middleware = (next) => {
  return async (ctx, req) => {
    ctx.log.info('Request started', { method: req.method, url: req.url });

    const response = await next(ctx, req);

    const duration = Date.now() - ctx.startTime;
    ctx.log.info('Request completed', { status: response.status, duration });

    return response;
  };
};

const handler = requireAuth(requestLogger(getUser));
// Request flow: requireAuth → requestLogger → getUser

export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'OPTIONS';

export type Route = {
  method: HttpMethod;
  path: string;
  handler: Handler;
  middleware?: Middleware[];
};

export type RouteMatch = {
  route: Route;
  params: Record<string, string>;
};

const router = createRouter();

// Add routes
router.get('/api/books', listBooks);
router.get('/api/books/:id', getBook);
router.post('/api/books', createBook, [requireAuth]);
router.put('/api/books/:id', updateBook, [requireAuth]);
router.delete('/api/books/:id', deleteBook, [requireAuth, requireAdmin]);

// Match request
const match = router.match('GET', '/api/books/123');
// match = { route: {...}, params: { id: '123' } }

export type AuthenticatedUser = {
  userId: number;         // Primary key from users table
  email: string;          // User's email address
  username: string | null; // Username (may be null)
  credentialId: number;   // Which credential was used (for multi-credential users)
  authMethod: string;     // How they authenticated (e.g., 'password', 'google')
};

export const createBook: Handler = async (ctx, req) => {
  // Require authentication
  if (!ctx.user) {
    return new Response('Unauthorized', { status: 401 });
  }

  const data = await req.json();

  // Use authenticated user ID
  const [book] = await ctx.sql`
    INSERT INTO books (user_id, title, author)
    VALUES (${ctx.user.userId}, ${data.title}, ${data.author})
    RETURNING *
  `;

  return new Response(JSON.stringify(book), { status: 201 });
};

import type { Handler } from '@/domains/types/http';

export const healthCheck: Handler = async (ctx, req) => {
  return new Response(JSON.stringify({ status: 'ok' }), {
    headers: { 'Content-Type': 'application/json' },
  });
};

import type { Handler } from '@/domains/types/http';

export const getBook: Handler = async (ctx, req) => {
  const bookId = parseInt(ctx.params.id, 10); // From /api/books/:id

  const [book] = await ctx.sql`
    SELECT * FROM books WHERE id = ${bookId}
  `;

  if (!book) {
    return new Response('Book not found', { status: 404 });
  }

  return new Response(JSON.stringify(book), {
    headers: { 'Content-Type': 'application/json' },
  });
};

import type { Handler } from '@/domains/types/http';

export const createBook: Handler = async (ctx, req) => {
  if (!ctx.user) {
    return new Response('Unauthorized', { status: 401 });
  }

  const data = await req.json();

  // Validate input
  if (!data.title || !data.author) {
    return new Response('Missing required fields', { status: 400 });
  }

  const [book] = await ctx.sql`
    INSERT INTO books (user_id, title, author)
    VALUES (${ctx.user.userId}, ${data.title}, ${data.author})
    RETURNING *
  `;

  return new Response(JSON.stringify(book), {
    status: 201,
    headers: { 'Content-Type': 'application/json' },
  });
};

import { createRouter } from '@/server/src/router';
import type { Handler } from '@/domains/types/http';

const router = createRouter();

// Public routes
router.get('/health', healthCheck);
router.post('/auth/login', login);

// Protected routes with middleware
router.get('/api/books', listBooks, [requireAuth]);
router.post('/api/books', createBook, [requireAuth]);
router.get('/api/books/:id', getBook, [requireAuth]);
router.put('/api/books/:id', updateBook, [requireAuth]);
router.delete('/api/books/:id', deleteBook, [requireAuth, requireAdmin]);

// Admin routes
router.get('/admin/users', listUsers, [requireAuth, requireAdmin]);

import { createContext } from '@/server/src/context';
import { getConnection } from '@quailcomp/data';

// 1. Create context for incoming request
const sql = getConnection();
const ctx = createContext(req, sql);

// 2. Match request to route
const match = router.match(req.method, new URL(req.url).pathname);

if (!match) {
  return new Response('Not Found', { status: 404 });
}

// 3. Populate params from route match
ctx.params = match.params;

// 4. Compose middleware and handler
let handler = match.route.handler;
for (const middleware of match.route.middleware ?? []) {
  handler = middleware(handler);
}

// 5. Execute handler
const response = await handler(ctx, req);

// 6. Return response
return response;

// No authentication required
router.get('/api/health', healthCheck);
router.get('/api/books/search', searchBooks); // Public search

// Require authentication
router.get('/api/profile', getProfile, [requireAuth]);
router.put('/api/profile', updateProfile, [requireAuth]);

// Require admin role
router.delete('/api/users/:id', deleteUser, [requireAuth, requireAdmin]);
router.get('/admin/metrics', getMetrics, [requireAuth, requireAdmin]);

// Apply logging/metrics to all routes
const withObservability = (handler: Handler): Handler => {
  return requestLogger(metricsMiddleware(handler));
};

router.get('/api/books', withObservability(listBooks));

// Wrap all routes with error handling
const withErrorHandling: Middleware = (next) => {
  return async (ctx, req) => {
    try {
      return await next(ctx, req);
    } catch (error) {
      ctx.log.error('Handler error', { error });
      return new Response(
        JSON.stringify({ error: 'Internal Server Error' }),
        { status: 500, headers: { 'Content-Type': 'application/json' } }
      );
    }
  };
};

router.get('/api/books', listBooks, [withErrorHandling]);

const rateLimit: Middleware = (next) => {
  const requests = new Map<string, number>();

  return async (ctx, req) => {
    const key = ctx.user?.userId.toString() ?? ctx.requestId;
    const count = requests.get(key) ?? 0;

    if (count >= 100) {
      return new Response('Too Many Requests', { status: 429 });
    }

    requests.set(key, count + 1);
    setTimeout(() => requests.delete(key), 60_000); // Reset after 1 min

    return next(ctx, req);
  };
};

router.post('/api/books', createBook, [requireAuth, rateLimit]);
