/**
 * Auto-generated from domains/logging.md
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * This file is automatically generated by devtools/watch/tasks/types-from-docs.ts
 * which extracts TypeScript code blocks from the markdown domain documentation.
 *
 * To make changes:
 * 1. Edit the corresponding .md file in /domains
 * 2. The devtools watcher will regenerate automatically
 * 3. Or run manually: bun run devtools/watch/tasks/types-from-docs.ts
 */

export type LogLevel = "debug" | "info" | "warn" | "error";

export type LogEntry = {
  level: LogLevel;
  message: string;
  timestamp: string; // ISO 8601 format
  [key: string]: unknown; // Arbitrary context data
};

export type Logger = {
  debug(message: string, data?: Record<string, unknown>): void;
  info(message: string, data?: Record<string, unknown>): void;
  warn(message: string, data?: Record<string, unknown>): void;
  error(message: string, data?: Record<string, unknown>): void;

  /** Create child logger with additional context */
  child(context: Record<string, unknown>): Logger;
};

export type LoggerOptions = {
  level?: LogLevel; // Minimum level to output (default: 'info')
  context?: Record<string, unknown>; // Persistent context added to all logs
};

import { createLogger } from '@/server/src/logging/logger';

const logger = createLogger({ level: 'info' });

logger.info('Server starting');
// {"level":"info","message":"Server starting","timestamp":"2026-02-06T10:30:00.000Z"}

logger.debug('Detailed debug info'); // Suppressed (below 'info' level)

logger.error('Failed to connect to database', {
  error: 'connection timeout',
  host: 'localhost',
  port: 5432,
});
// {"level":"error","message":"Failed to connect to database","timestamp":"...","error":"connection timeout","host":"localhost","port":5432}

import { createLogger } from '@/server/src/logging/logger';

const rootLogger = createLogger();

// Create child logger with request context
const requestLogger = rootLogger.child({
  request_id: 'req_abc123',
  user_id: 42,
  method: 'GET',
  path: '/api/books',
});

// All logs from requestLogger include request context
requestLogger.info('Processing request');
// {"level":"info","message":"Processing request","timestamp":"...","request_id":"req_abc123","user_id":42,"method":"GET","path":"/api/books"}

requestLogger.info('Database query executed', { duration_ms: 15 });
// {"level":"info","message":"Database query executed","timestamp":"...","request_id":"req_abc123","user_id":42,"method":"GET","path":"/api/books","duration_ms":15}

import { createLogger } from '@/server/src/logging/logger';
import type { RequestContext } from '@/server/src/context';

// Create request-scoped logger in middleware
function createRequestContext(req: Request): RequestContext {
  const requestId = crypto.randomUUID();

  const logger = createLogger().child({
    request_id: requestId,
    method: req.method,
    path: new URL(req.url).pathname,
  });

  return {
    request_id: requestId,
    logger,
    // ... other context fields
  };
}

// Use logger throughout request lifecycle
async function handleRequest(ctx: RequestContext) {
  ctx.logger.info('Request started');

  try {
    const result = await fetchData(ctx);
    ctx.logger.info('Request completed', { status: 200 });
    return new Response(JSON.stringify(result));
  } catch (error) {
    ctx.logger.error('Request failed', {
      error: error instanceof Error ? error.message : String(error),
      stack: error instanceof Error ? error.stack : undefined,
    });
    throw error;
  }
}

import { createLogger } from '@/server/src/logging/logger';
import { env, isDevelopment } from '@/server/src/config';

// Use LOG_LEVEL from configuration
const logger = createLogger({ level: env.LOG_LEVEL });

// Development-only debug logs
if (isDevelopment()) {
  logger.debug('Configuration loaded', {
    port: env.PORT,
    database: env.DATABASE_URL,
  });
}

import { createLogger } from '@/server/src/logging/logger';

const logger = createLogger();

try {
  await riskyOperation();
} catch (error) {
  logger.error('Operation failed', {
    error_message: error instanceof Error ? error.message : String(error),
    error_stack: error instanceof Error ? error.stack : undefined,
    operation: 'riskyOperation',
  });
  throw error;
}

export type LoggerFactory = (options?: LoggerOptions) => Logger;

// Middleware creates request logger
app.use((ctx, next) => {
  ctx.logger = rootLogger.child({
    request_id: ctx.request_id,
    method: ctx.request.method,
    path: ctx.request.url,
  });

  ctx.logger.info('Request started');
  return next();
});

// Handlers use request logger
async function getBooks(ctx: RequestContext) {
  ctx.logger.info('Fetching books');
  const books = await db.getBooks(ctx.sql);
  ctx.logger.info('Books fetched', { count: books.length });
  return books;
}

class BookMetadataService {
  private logger: Logger;

  constructor(logger: Logger) {
    this.logger = logger.child({ service: 'BookMetadataService' });
  }

  async fetchMetadata(isbn: string): Promise<BookMetadata> {
    this.logger.info('Fetching metadata', { isbn });

    try {
      const metadata = await this.provider.lookup(isbn);
      this.logger.info('Metadata fetched successfully', { isbn, provider: metadata.provider });
      return metadata;
    } catch (error) {
      this.logger.error('Metadata fetch failed', {
        isbn,
        error: error instanceof Error ? error.message : String(error),
      });
      throw error;
    }
  }
}

async function queryDatabase(ctx: RequestContext, query: string) {
  const start = Date.now();

  try {
    const result = await ctx.sql.query(query);
    const duration = Date.now() - start;

    ctx.logger.info('Query executed', {
      query_type: 'select',
      duration_ms: duration,
      row_count: result.length,
    });

    return result;
  } catch (error) {
    const duration = Date.now() - start;

    ctx.logger.error('Query failed', {
      query_type: 'select',
      duration_ms: duration,
      error: error instanceof Error ? error.message : String(error),
    });

    throw error;
  }
}

import { isDevelopment } from '@/server/src/config';

async function processBook(ctx: RequestContext, bookId: number) {
  if (isDevelopment()) {
    ctx.logger.debug('Processing book', { bookId });
  }

  const book = await fetchBook(ctx, bookId);

  if (isDevelopment()) {
    ctx.logger.debug('Book fetched', {
      bookId,
      title: book.title,
      author: book.author,
    });
  }

  return book;
}

// ❌ Bad - repeating context
logger.info('Request started', { request_id, user_id });
logger.info('Query executed', { request_id, user_id, duration_ms });

// ✅ Good - child logger with persistent context
const requestLogger = logger.child({ request_id, user_id });
requestLogger.info('Request started');
requestLogger.info('Query executed', { duration_ms });

// ❌ Bad - string interpolation loses structure
logger.info(`User ${userId} created book ${bookId}`);

// ✅ Good - structured data is queryable
logger.info('User created book', { user_id: userId, book_id: bookId });

// ❌ Bad - unclear what failed
logger.error('Database query failed');

// ✅ Good - clear context for debugging
logger.error('Database query failed', {
  operation: 'fetchUserBooks',
  user_id: userId,
  error: error.message,
});
