/**
 * Auto-generated from domains/metrics.md
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * This file is automatically generated by devtools/watch/tasks/types-from-docs.ts
 * which extracts TypeScript code blocks from the markdown domain documentation.
 *
 * To make changes:
 * 1. Edit the corresponding .md file in /domains
 * 2. The devtools watcher will regenerate automatically
 * 3. Or run manually: bun run devtools/watch/tasks/types-from-docs.ts
 */

export type Counter = {
  name: string; // Metric name (e.g., 'http_requests_total')
  labels: Record<string, string>; // Dimensions (e.g., {method: 'GET', status: '200'})
  value: number; // Current count
};

export type Histogram = {
  name: string; // Metric name (e.g., 'http_request_duration_ms')
  labels: Record<string, string>; // Dimensions (e.g., {method: 'GET', path: '/api/books'})
  count: number; // Total number of observations
  sum: number; // Sum of all observed values
  buckets: Map<number, number>; // Cumulative counts per bucket threshold
};

export type MetricsSnapshot = {
  counters: Counter[];
  histograms: Array<{
    name: string;
    labels: Record<string, string>;
    count: number;
    sum: number;
    avg: number; // Calculated: sum / count
    buckets: Record<string, number>; // Serialized from Map
  }>;
  timestamp: string; // ISO 8601 timestamp
};
