/**
 * Auto-generated from domains/metrics.md
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * This file is automatically generated by domains/scripts/extract-types.ts
 * which extracts TypeScript code blocks from the markdown domain documentation.
 *
 * To make changes:
 * 1. Edit the corresponding .md file in /domains
 * 2. Run: bun run domains/scripts/extract-types.ts
 * 3. Or commit changes - the pre-commit hook will regenerate automatically
 */

export type Counter = {
  name: string; // Metric name (e.g., 'http_requests_total')
  labels: Record<string, string>; // Dimensions (e.g., {method: 'GET', status: '200'})
  value: number; // Current count
};

export type Histogram = {
  name: string; // Metric name (e.g., 'http_request_duration_ms')
  labels: Record<string, string>; // Dimensions (e.g., {method: 'GET', path: '/api/books'})
  count: number; // Total number of observations
  sum: number; // Sum of all observed values
  buckets: Map<number, number>; // Cumulative counts per bucket threshold
};

export type MetricsSnapshot = {
  counters: Counter[];
  histograms: Array<{
    name: string;
    labels: Record<string, string>;
    count: number;
    sum: number;
    avg: number; // Calculated: sum / count
    buckets: Record<string, number>; // Serialized from Map
  }>;
  timestamp: string; // ISO 8601 timestamp
};

// HTTP requests by method and status
metrics.inc('http_requests_total', { method: 'GET', status: '200' });
metrics.inc('http_requests_total', { method: 'POST', status: '201' });
metrics.inc('http_requests_total', { method: 'GET', status: '404' });

// Request latency by method and path
metrics.observe('http_request_duration_ms', { method: 'GET', path: '/api/books' }, 42);
metrics.observe('http_request_duration_ms', { method: 'POST', path: '/api/books' }, 156);

import { metrics } from '@/server/src/metrics/collector';

// Count HTTP requests
metrics.inc('http_requests_total', {
  method: req.method,
  path: route.path,
  status: String(response.status),
});

// Count errors
metrics.inc('http_errors_total', {
  method: req.method,
  error_type: 'validation_error',
});

// Count cache hits/misses
if (cached) {
  metrics.inc('cache_hits_total', { cache_type: 'book_metadata' });
} else {
  metrics.inc('cache_misses_total', { cache_type: 'book_metadata' });
}

import { metrics } from '@/server/src/metrics/collector';

const start = Date.now();

try {
  const result = await handler(ctx, req);
  const duration = Date.now() - start;

  // Record successful request latency
  metrics.observe('http_request_duration_ms', {
    method: req.method,
    path: route.path,
    status: '200',
  }, duration);

  return result;
} catch (error) {
  const duration = Date.now() - start;

  // Record failed request latency
  metrics.observe('http_request_duration_ms', {
    method: req.method,
    path: route.path,
    status: '500',
  }, duration);

  throw error;
}

import { metrics } from '@/server/src/metrics/collector';

async function queryDatabase<T>(sql: Sql, query: string): Promise<T[]> {
  const start = Date.now();

  try {
    const result = await sql.query<T>(query);
    const duration = Date.now() - start;

    metrics.inc('database_queries_total', { query_type: 'select', status: 'success' });
    metrics.observe('database_query_duration_ms', { query_type: 'select' }, duration);

    return result;
  } catch (error) {
    const duration = Date.now() - start;

    metrics.inc('database_queries_total', { query_type: 'select', status: 'error' });
    metrics.observe('database_query_duration_ms', { query_type: 'select' }, duration);

    throw error;
  }
}

import { metrics } from '@/server/src/metrics/collector';

async function fetchBookMetadata(provider: string, isbn: string): Promise<BookMetadata> {
  const start = Date.now();

  try {
    const metadata = await providerClient.lookup(isbn);
    const duration = Date.now() - start;

    metrics.inc('metadata_lookups_total', { provider, status: 'success' });
    metrics.observe('metadata_lookup_duration_ms', { provider }, duration);

    return metadata;
  } catch (error) {
    const duration = Date.now() - start;

    metrics.inc('metadata_lookups_total', { provider, status: 'error' });
    metrics.observe('metadata_lookup_duration_ms', { provider }, duration);

    throw error;
  }
}

import { metrics } from '@/server/src/metrics/collector';
import type { RequestContext } from '@/server/src/context';

async function handleMetrics(ctx: RequestContext): Promise<Response> {
  const snapshot = metrics.snapshot();

  // Format counters
  const counterLines = snapshot.counters.map((c) => {
    const labelStr = Object.entries(c.labels)
      .map(([k, v]) => `${k}="${v}"`)
      .join(',');
    return `${c.name}{${labelStr}} ${c.value}`;
  });

  // Format histograms
  const histogramLines = snapshot.histograms.flatMap((h) => {
    const labelStr = Object.entries(h.labels)
      .map(([k, v]) => `${k}="${v}"`)
      .join(',');

    const lines = [
      `${h.name}_count{${labelStr}} ${h.count}`,
      `${h.name}_sum{${labelStr}} ${h.sum}`,
    ];

    // Add bucket lines
    Object.entries(h.buckets).forEach(([bucket, count]) => {
      lines.push(`${h.name}_bucket{${labelStr},le="${bucket}"} ${count}`);
    });

    return lines;
  });

  const output = [...counterLines, ...histogramLines].join('\n');

  return new Response(output, {
    headers: { 'Content-Type': 'text/plain; version=0.0.4' },
  });
}

import { metrics } from '@/server/src/metrics/collector';

async function handleHealthCheck(): Promise<Response> {
  const snapshot = metrics.snapshot();

  // Calculate error rate
  const requestsCounter = snapshot.counters.find((c) =>
    c.name === 'http_requests_total'
  );
  const errorsCounter = snapshot.counters.find((c) =>
    c.name === 'http_errors_total'
  );

  const totalRequests = requestsCounter?.value ?? 0;
  const totalErrors = errorsCounter?.value ?? 0;
  const errorRate = totalRequests > 0 ? totalErrors / totalRequests : 0;

  // Check average latency
  const latencyHistogram = snapshot.histograms.find((h) =>
    h.name === 'http_request_duration_ms'
  );
  const avgLatency = latencyHistogram?.avg ?? 0;

  const health = {
    status: errorRate < 0.05 && avgLatency < 1000 ? 'healthy' : 'degraded',
    error_rate: errorRate,
    avg_latency_ms: avgLatency,
    total_requests: totalRequests,
  };

  return new Response(JSON.stringify(health), {
    headers: { 'Content-Type': 'application/json' },
  });
}

// Periodically poll metrics for dashboard
setInterval(async () => {
  const snapshot = metrics.snapshot();

  const requestRate = calculateRate(snapshot.counters, 'http_requests_total');
  const errorRate = calculateErrorRate(snapshot.counters);
  const p95Latency = calculateP95(snapshot.histograms, 'http_request_duration_ms');

  await updateDashboard({
    request_rate: requestRate,
    error_rate: errorRate,
    p95_latency: p95Latency,
  });
}, 5000); // Poll every 5 seconds

// Check metrics and trigger alerts
async function checkAlerts() {
  const snapshot = metrics.snapshot();

  const latencyHistogram = snapshot.histograms.find((h) =>
    h.name === 'http_request_duration_ms' && h.labels.path === '/api/books'
  );

  if (latencyHistogram && latencyHistogram.avg > 1000) {
    await sendAlert({
      severity: 'warning',
      message: 'High latency on /api/books endpoint',
      avg_latency_ms: latencyHistogram.avg,
    });
  }
}

// Analyze metrics after load test
async function analyzeLoadTest() {
  const snapshot = metrics.snapshot();

  const latencyHistogram = snapshot.histograms.find((h) =>
    h.name === 'http_request_duration_ms'
  );

  if (!latencyHistogram) return;

  console.log('Load Test Results:');
  console.log(`Total requests: ${latencyHistogram.count}`);
  console.log(`Average latency: ${latencyHistogram.avg.toFixed(2)}ms`);
  console.log(`Total duration: ${latencyHistogram.sum}ms`);

  // Calculate percentiles from buckets
  const p50 = findPercentileBucket(latencyHistogram.buckets, 0.5, latencyHistogram.count);
  const p95 = findPercentileBucket(latencyHistogram.buckets, 0.95, latencyHistogram.count);
  const p99 = findPercentileBucket(latencyHistogram.buckets, 0.99, latencyHistogram.count);

  console.log(`p50 latency: ≤${p50}ms`);
  console.log(`p95 latency: ≤${p95}ms`);
  console.log(`p99 latency: ≤${p99}ms`);
}

// ✅ Good - consistent labels across metrics
metrics.inc('http_requests_total', { method: 'GET', path: '/api/books' });
metrics.observe('http_request_duration_ms', { method: 'GET', path: '/api/books' }, 42);

// ❌ Bad - inconsistent label names
metrics.inc('http_requests_total', { http_method: 'GET', route: '/api/books' });
metrics.observe('http_request_duration_ms', { method: 'GET', path: '/api/books' }, 42);

// ❌ Bad - user_id creates millions of time series
metrics.inc('requests_total', { user_id: String(userId) });

// ✅ Good - user_type has low cardinality
metrics.inc('requests_total', { user_type: user.is_premium ? 'premium' : 'free' });

// ✅ Good - clear names with units
metrics.inc('http_requests_total');
metrics.observe('http_request_duration_ms', labels, duration);
metrics.observe('database_query_duration_ms', labels, duration);

// ❌ Bad - unclear names without units
metrics.inc('requests');
metrics.observe('latency', labels, duration);

// ✅ Good - reset in test teardown
afterEach(() => {
  metrics.reset();
});

// ❌ Bad - resetting in production loses data
if (isProduction()) {
  metrics.reset(); // Never do this!
}
