/**
 * Auto-generated from domains/people.md
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * This file is automatically generated by domains/scripts/extract-types.ts
 * which extracts TypeScript code blocks from the markdown domain documentation.
 *
 * To make changes:
 * 1. Edit the corresponding .md file in /domains
 * 2. Run: bun run domains/scripts/extract-types.ts
 * 3. Or commit changes - the pre-commit hook will regenerate automatically
 */

export type Person = {
  entity_id: string
  name: string
  email?: string
  phone?: string
  notes?: string
  relationships: PersonRelationship[]
}
export type PersonRelationship =
  | 'author'
  | 'contributor'
  | 'gift_giver'
  | 'borrower'
  | 'other'
export type PersonEntitySnapshot = {
  name: string
  email?: string
  phone?: string
  notes?: string
  relationships: PersonRelationship[]
}
export type PersonEntityRow = {
  entity_id: number
  entity_type: 'person'
  data: PersonEntitySnapshot
  created_at: Date
  updated_at: Date
  deleted_at: Date | null
}

export type PersonListItem = {
  entity_id: string
  name: string
  relationships: PersonRelationship[]
  book_count?: number
}
export type PersonWithBooks = {
  person: Person
  books_given?: number
  books_borrowed?: number
}
