/**
 * Auto-generated from domains/series.md
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * This file is automatically generated by devtools/watch/tasks/types-from-docs.ts
 * which extracts TypeScript code blocks from the markdown domain documentation.
 *
 * To make changes:
 * 1. Edit the corresponding .md file in /domains
 * 2. The devtools watcher will regenerate automatically
 * 3. Or run manually: bun run devtools/watch/tasks/types-from-docs.ts
 */

export type Series = {
  entity_id: string
  name: string
  total_volumes?: number
  notes?: string
}
export type SeriesEntitySnapshot = {
  name: string
  total_volumes?: number
  notes?: string
}
export type SeriesEntityRow = {
  entity_id: number
  entity_type: 'series'
  data: SeriesEntitySnapshot
  created_at: Date
  updated_at: Date
  deleted_at: Date | null
}

import type { PhysicalBook } from "./books";
export type SeriesListItem = {
  entity_id: string
  name: string
  total_volumes?: number
  book_count?: number
}
export type BookInSeries = {
  book_id: string
  series_id: string
  volume_number?: number
  volume_name?: string
}
export type SeriesWithBooks = {
  series: Series
  books: Array<{
    book: PhysicalBook
    volume_number?: number
    volume_name?: string
  }>
}
