/**
 * Auto-generated from domains/websocket.md
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * This file is automatically generated by devtools/watch/tasks/types-from-docs.ts
 * which extracts TypeScript code blocks from the markdown domain documentation.
 *
 * To make changes:
 * 1. Edit the corresponding .md file in /domains
 * 2. The devtools watcher will regenerate automatically
 * 3. Or run manually: bun run devtools/watch/tasks/types-from-docs.ts
 */

export interface WebSocketData {
  /** User ID from authenticated JWT token */
  userId: number;
  /** Set of entity IDs this connection is subscribed to */
  subscriptions: Set<number>;
  /** Whether this connection has successfully authenticated */
  authenticated: boolean;
}

export interface WebSocketMessage {
  /** Message type indicating the action */
  type: "subscribe" | "unsubscribe" | "ping" | "error" | "authenticated";
  /** Entity ID for subscribe/unsubscribe actions */
  entityId?: number;
  /** Error or status message */
  message?: string;
}

export interface BroadcastMessage {
  /** Type of entity change */
  type: "entity.created" | "entity.updated" | "entity.deleted";
  /** ID of the affected entity */
  entityId: number;
  /** Entity type string (e.g., "book", "series") */
  entityType: string;
  /** Optional entity data (depends on event type) */
  data?: unknown;
  /** ISO timestamp of when the event occurred */
  timestamp: string;
}
